ESP RFID Webui: AsyncTCP.cpp File Reference
AsyncTCP.cpp File Reference
#include "Arduino.h"
#include "AsyncTCP.h"
#include "lwip/dns.h"
#include "lwip/err.h"
#include "lwip/inet.h"
#include "lwip/opt.h"
#include "lwip/tcp.h"
#include "esp_task_wdt.h"
#include "lwip/priv/tcpip_priv.h"
Data Structures
struct lwip_event_packet_t
struct tcp_api_call_t
Macros
#define TAG "AsyncTCP"
#define TCP_MUTEX_LOCK()
#define TCP_MUTEX_UNLOCK()
#define INVALID_CLOSED_SLOT -1
#define CONFIG_ASYNC_TCP_POLL_TIMER 1
Enumerations
enum lwip_event_t {
LWIP_TCP_SENT , LWIP_TCP_RECV , LWIP_TCP_FIN , LWIP_TCP_ERROR ,
LWIP_TCP_POLL , LWIP_TCP_CLEAR , LWIP_TCP_ACCEPT , LWIP_TCP_CONNECTED ,
LWIP_TCP_DNS
}
Functions
static bool _init_async_event_queue ()
static bool _send_async_event (lwip_event_packet_t **e, TickType_t wait=portMAX_DELAY)
static bool _prepend_async_event (lwip_event_packet_t **e, TickType_t wait=portMAX_DELAY)
static bool _get_async_event (lwip_event_packet_t **e)
static bool _remove_events_with_arg (void *arg)
static void _handle_async_event (lwip_event_packet_t *e)
static void _async_service_task (void *pvParameters)
static bool customTaskCreateUniversal (TaskFunction_t pxTaskCode, const char *const pcName, const uint32_t usStackDepth, void *const pvParameters, UBaseType_t uxPriority, TaskHandle_t *const pxCreatedTask, const BaseType_t xCoreID)
static bool _start_async_task ()
static int8_t _tcp_clear_events (void *arg)
static int8_t _tcp_connected (void *arg, tcp_pcb *pcb, int8_t err)
static int8_t _tcp_poll (void *arg, struct tcp_pcb *pcb)
static int8_t _tcp_recv (void *arg, struct tcp_pcb *pcb, struct pbuf *pb, int8_t err)
static int8_t _tcp_sent (void *arg, struct tcp_pcb *pcb, uint16_t len)
static void _tcp_error (void *arg, int8_t err)
static void _tcp_dns_found (const char *name, struct ip_addr *ipaddr, void *arg)
static int8_t _tcp_accept (void *arg, AsyncClient *client)
static err_t _tcp_output_api (struct tcpip_api_call_data *api_call_msg)
static esp_err_t _tcp_output (tcp_pcb *pcb, int8_t closed_slot)
static err_t _tcp_write_api (struct tcpip_api_call_data *api_call_msg)
static esp_err_t _tcp_write (tcp_pcb *pcb, int8_t closed_slot, const char *data, size_t size, uint8_t apiflags)
static err_t _tcp_recved_api (struct tcpip_api_call_data *api_call_msg)
static esp_err_t _tcp_recved (tcp_pcb *pcb, int8_t closed_slot, size_t len)
static err_t _tcp_close_api (struct tcpip_api_call_data *api_call_msg)
static esp_err_t _tcp_close (tcp_pcb *pcb, int8_t closed_slot)
static err_t _tcp_abort_api (struct tcpip_api_call_data *api_call_msg)
static esp_err_t _tcp_abort (tcp_pcb *pcb, int8_t closed_slot)
static err_t _tcp_connect_api (struct tcpip_api_call_data *api_call_msg)
static esp_err_t _tcp_connect (tcp_pcb *pcb, int8_t closed_slot, ip_addr_t *addr, uint16_t port, tcp_connected_fn cb)
static err_t _tcp_bind_api (struct tcpip_api_call_data *api_call_msg)
static esp_err_t _tcp_bind (tcp_pcb *pcb, ip_addr_t *addr, uint16_t port)
static err_t _tcp_listen_api (struct tcpip_api_call_data *api_call_msg)
static tcp_pcb * _tcp_listen_with_backlog (tcp_pcb *pcb, uint8_t backlog)
Variables
static QueueHandle_t _async_queue
static TaskHandle_t _async_service_task_handle = NULL
SemaphoreHandle_t _slots_lock
const int _number_of_closed_slots = CONFIG_LWIP_MAX_ACTIVE_TCP
static uint32_t _closed_slots [_number_of_closed_slots]
static uint32_t _closed_index
Macro Definition Documentation
CONFIG_ASYNC_TCP_POLL_TIMER
#define CONFIG_ASYNC_TCP_POLL_TIMER 1
Definition at line 68 of file AsyncTCP.cpp.
Referenced by AsyncClient::_connect(), AsyncClient::AsyncClient(), and AsyncClient::operator=().
INVALID_CLOSED_SLOT
#define INVALID_CLOSED_SLOT -1
Definition at line 62 of file AsyncTCP.cpp.
Referenced by AsyncClient::_allocate_closed_slot(), AsyncClient::_free_closed_slot(), _tcp_abort_api(), _tcp_close_api(), _tcp_output_api(), _tcp_recved_api(), _tcp_write_api(), and AsyncClient::AsyncClient().
TAG
#define TAG "AsyncTCP"
Definition at line 44 of file AsyncTCP.cpp.
TCP_MUTEX_LOCK
#define TCP_MUTEX_LOCK ()
Definition at line 58 of file AsyncTCP.cpp.
Referenced by AsyncClient::_close(), AsyncClient::_connect(), AsyncClient::_error(), AsyncServer::begin(), AsyncClient::connect(), and AsyncServer::end().
TCP_MUTEX_UNLOCK
#define TCP_MUTEX_UNLOCK ()
Definition at line 59 of file AsyncTCP.cpp.
Referenced by AsyncClient::_close(), AsyncClient::_connect(), AsyncClient::_error(), AsyncServer::begin(), AsyncClient::connect(), and AsyncServer::end().
Enumeration Type Documentation
lwip_event_t
enum lwip_event_t
Enumerator
LWIP_TCP_SENT
LWIP_TCP_RECV
LWIP_TCP_FIN
LWIP_TCP_ERROR
LWIP_TCP_POLL
LWIP_TCP_CLEAR
LWIP_TCP_ACCEPT
LWIP_TCP_CONNECTED
LWIP_TCP_DNS
Definition at line 74 of file AsyncTCP.cpp.
             {
  LWIP_TCP_SENT,
  LWIP_TCP_RECV,
  LWIP_TCP_FIN,
  LWIP_TCP_ERROR,
  LWIP_TCP_POLL,
  LWIP_TCP_CLEAR,
  LWIP_TCP_ACCEPT,
  LWIP_TCP_CONNECTED,
  LWIP_TCP_DNS
} lwip_event_t;
Function Documentation
_async_service_task()
void _async_service_task (void * pvParameters) static
Definition at line 298 of file AsyncTCP.cpp.
{
#if CONFIG_ASYNC_TCP_USE_WDT
  if (esp_task_wdt_add(NULL) != ESP_OK) {
    log_w("Failed to add async task to WDT");
  }
#endif
  lwip_event_packet_t* packet = NULL;
  for (;;) {
    if (_get_async_event(&packet)) {
      _handle_async_event(packet);
    }
#if CONFIG_ASYNC_TCP_USE_WDT
    esp_task_wdt_reset();
#endif
  }
#if CONFIG_ASYNC_TCP_USE_WDT
  esp_task_wdt_delete(NULL);
#endif
  vTaskDelete(NULL);
  _async_service_task_handle = NULL;
}
References _async_service_task_handle, _get_async_event(), and _handle_async_event().
Referenced by _start_async_task().
_get_async_event()
bool _get_async_event (lwip_event_packet_t ** e) inline static
Definition at line 156 of file AsyncTCP.cpp.
{
  if (!_async_queue) {
    return false;
  }
#if CONFIG_ASYNC_TCP_USE_WDT
  // need to return periodically to feed the dog
  if (xQueueReceive(_async_queue, e, pdMS_TO_TICKS(1000)) != pdPASS)
    return false;
#else
  if (xQueueReceive(_async_queue, e, portMAX_DELAY) != pdPASS)
    return false;
#endif
  if ((*e)->event != LWIP_TCP_POLL)
    return true;
  /*
    Let's try to coalesce two (or more) consecutive poll events into one
    this usually happens with poor implemented user-callbacks that are runs too long and makes poll events to stack in the queue
    if consecutive user callback for a same connection runs longer that poll time then it will fill the queue with events until it deadlocks.
    This is a workaround to mitigate such poor designs and won't let other events/connections to starve the task time.
    It won't be effective if user would run multiple simultaneous long running callbacks due to message interleaving.
    todo: implement some kind of fair dequeing or (better) simply punish user for a bad designed callbacks by resetting hog connections
  */
  lwip_event_packet_t* next_pkt = NULL;
  while (xQueuePeek(_async_queue, &next_pkt, 0) == pdPASS) {
    if (next_pkt->arg == (*e)->arg && next_pkt->event == LWIP_TCP_POLL) {
      if (xQueueReceive(_async_queue, &next_pkt, 0) == pdPASS) {
        free(next_pkt);
        next_pkt = NULL;
        log_d("coalescing polls, network congestion or async callbacks might be too slow!");
        continue;
      }
    }
    // quit while loop if next event can't be discarded
    break;
  }
  /*
    now we have to decide if to proceed with poll callback handler or discard it?
    poor designed apps using asynctcp without proper dataflow control could flood the queue with interleaved pool/ack events.
    I.e. on each poll app would try to generate more data to send, which in turn results in additional ack event triggering chain effect
    for long connections. Or poll callback could take long time starving other connections. Anyway our goal is to keep the queue length
    grows under control (if possible) and poll events are the safest to discard.
    Let's discard poll events processing using linear-increasing probability curve when queue size grows over 3/4
    Poll events are periodic and connection could get another chance next time
  */
  if (uxQueueMessagesWaiting(_async_queue) > (rand() % CONFIG_ASYNC_TCP_QUEUE_SIZE / 4 + CONFIG_ASYNC_TCP_QUEUE_SIZE * 3 / 4)) {
    free(*e);
    *e = NULL;
    log_d("discarding poll due to queue congestion");
    // evict next event from a queue
    return _get_async_event(e);
  }
  // last resort return
  return true;
}
References _async_queue, _get_async_event(), lwip_event_packet_t::arg, CONFIG_ASYNC_TCP_QUEUE_SIZE, lwip_event_packet_t::event, and LWIP_TCP_POLL.
Referenced by _async_service_task(), and _get_async_event().
_handle_async_event()
void _handle_async_event (lwip_event_packet_t * e) static
Definition at line 264 of file AsyncTCP.cpp.
{
  if (e->arg == NULL) {
    // do nothing when arg is NULL
    // ets_printf("event arg == NULL: 0x%08x\n", e->recv.pcb);
  } else if (e->event == LWIP_TCP_CLEAR) {
    _remove_events_with_arg(e->arg);
  } else if (e->event == LWIP_TCP_RECV) {
    // ets_printf("-R: 0x%08x\n", e->recv.pcb);
    AsyncClient::_s_recv(e->arg, e->recv.pcb, e->recv.pb, e->recv.err);
  } else if (e->event == LWIP_TCP_FIN) {
    // ets_printf("-F: 0x%08x\n", e->fin.pcb);
    AsyncClient::_s_fin(e->arg, e->fin.pcb, e->fin.err);
  } else if (e->event == LWIP_TCP_SENT) {
    // ets_printf("-S: 0x%08x\n", e->sent.pcb);
    AsyncClient::_s_sent(e->arg, e->sent.pcb, e->sent.len);
  } else if (e->event == LWIP_TCP_POLL) {
    // ets_printf("-P: 0x%08x\n", e->poll.pcb);
    AsyncClient::_s_poll(e->arg, e->poll.pcb);
  } else if (e->event == LWIP_TCP_ERROR) {
    // ets_printf("-E: 0x%08x %d\n", e->arg, e->error.err);
    AsyncClient::_s_error(e->arg, e->error.err);
  } else if (e->event == LWIP_TCP_CONNECTED) {
    // ets_printf("C: 0x%08x 0x%08x %d\n", e->arg, e->connected.pcb, e->connected.err);
    AsyncClient::_s_connected(e->arg, e->connected.pcb, e->connected.err);
  } else if (e->event == LWIP_TCP_ACCEPT) {
    // ets_printf("A: 0x%08x 0x%08x\n", e->arg, e->accept.client);
    AsyncServer::_s_accepted(e->arg, e->accept.client);
  } else if (e->event == LWIP_TCP_DNS) {
    // ets_printf("D: 0x%08x %s = %s\n", e->arg, e->dns.name, ipaddr_ntoa(&e->dns.addr));
    AsyncClient::_s_dns_found(e->dns.name, &e->dns.addr, e->arg);
  }
  free((void*)(e));
}
References _remove_events_with_arg(), AsyncServer::_s_accepted(), AsyncClient::_s_connected(), AsyncClient::_s_dns_found(), AsyncClient::_s_error(), AsyncClient::_s_fin(), AsyncClient::_s_poll(), AsyncClient::_s_recv(), AsyncClient::_s_sent(), lwip_event_packet_t::accept, lwip_event_packet_t::addr, lwip_event_packet_t::arg, lwip_event_packet_t::client, lwip_event_packet_t::connected, lwip_event_packet_t::dns, lwip_event_packet_t::err, lwip_event_packet_t::error, lwip_event_packet_t::event, lwip_event_packet_t::fin, lwip_event_packet_t::len, LWIP_TCP_ACCEPT, LWIP_TCP_CLEAR, LWIP_TCP_CONNECTED, LWIP_TCP_DNS, LWIP_TCP_ERROR, LWIP_TCP_FIN, LWIP_TCP_POLL, LWIP_TCP_RECV, LWIP_TCP_SENT, lwip_event_packet_t::name, lwip_event_packet_t::pb, lwip_event_packet_t::pcb, lwip_event_packet_t::poll, lwip_event_packet_t::recv, and lwip_event_packet_t::sent.
Referenced by _async_service_task().
_init_async_event_queue()
bool _init_async_event_queue () inline static
Definition at line 138 of file AsyncTCP.cpp.
{
  if (!_async_queue) {
    _async_queue = xQueueCreate(CONFIG_ASYNC_TCP_QUEUE_SIZE, sizeof(lwip_event_packet_t*));
    if (!_async_queue) {
      return false;
    }
  }
  return true;
}
References _async_queue, and CONFIG_ASYNC_TCP_QUEUE_SIZE.
Referenced by _start_async_task().
_prepend_async_event()
bool _prepend_async_event (lwip_event_packet_t ** e, TickType_t wait = portMAX_DELAY) inline static
Definition at line 152 of file AsyncTCP.cpp.
{
  return _async_queue && xQueueSendToFront(_async_queue, e, wait) == pdPASS;
}
References _async_queue.
Referenced by _tcp_accept(), _tcp_clear_events(), and _tcp_connected().
_remove_events_with_arg()
bool _remove_events_with_arg (void * arg) static
Definition at line 217 of file AsyncTCP.cpp.
{
  if (!_async_queue) {
    return false;
  }
  lwip_event_packet_t* first_packet = NULL;
  lwip_event_packet_t* packet = NULL;
  // figure out which is the first non-matching packet so we can keep the order
  while (!first_packet) {
    if (xQueueReceive(_async_queue, &first_packet, 0) != pdPASS) {
      return false;
    }
    // discard packet if matching
    if ((int)first_packet->arg == (int)arg) {
      free(first_packet);
      first_packet = NULL;
    } else if (xQueueSend(_async_queue, &first_packet, 0) != pdPASS) {
      // try to return first packet to the back of the queue
      // we can't wait here if queue is full, because this call has been done from the only consumer task of this queue
      // otherwise it would deadlock, we have to discard the event
      free(first_packet);
      first_packet = NULL;
      return false;
    }
  }
  while (xQueuePeek(_async_queue, &packet, 0) == pdPASS && packet != first_packet) {
    if (xQueueReceive(_async_queue, &packet, 0) != pdPASS) {
      return false;
    }
    if ((int)packet->arg == (int)arg) {
      // remove matching event
      free(packet);
      packet = NULL;
      // otherwise try to requeue it
    } else if (xQueueSend(_async_queue, &packet, 0) != pdPASS) {
      // we can't wait here if queue is full, because this call has been done from the only consumer task of this queue
      // otherwise it would deadlock, we have to discard the event
      free(packet);
      packet = NULL;
      return false;
    }
  }
  return true;
}
References _async_queue, and lwip_event_packet_t::arg.
Referenced by _handle_async_event().
_send_async_event()
bool _send_async_event (lwip_event_packet_t ** e, TickType_t wait = portMAX_DELAY) inline static
Definition at line 148 of file AsyncTCP.cpp.
{
  return _async_queue && xQueueSend(_async_queue, e, wait) == pdPASS;
}
References _async_queue.
Referenced by _tcp_dns_found(), _tcp_error(), _tcp_poll(), _tcp_recv(), and _tcp_sent().
_start_async_task()
bool _start_async_task () static
Definition at line 347 of file AsyncTCP.cpp.
{
  if (!_init_async_event_queue()) {
    return false;
  }
  if (!_async_service_task_handle) {
    customTaskCreateUniversal(_async_service_task, "async_tcp", CONFIG_ASYNC_TCP_STACK_SIZE, NULL, CONFIG_ASYNC_TCP_PRIORITY, &_async_service_task_handle, CONFIG_ASYNC_TCP_RUNNING_CORE);
    if (!_async_service_task_handle) {
      return false;
    }
  }
  return true;
}
References _async_service_task(), _async_service_task_handle, _init_async_event_queue(), CONFIG_ASYNC_TCP_PRIORITY, CONFIG_ASYNC_TCP_RUNNING_CORE, CONFIG_ASYNC_TCP_STACK_SIZE, and customTaskCreateUniversal().
Referenced by AsyncClient::_connect(), AsyncServer::begin(), and AsyncClient::connect().
_tcp_abort()
esp_err_t _tcp_abort (tcp_pcb * pcb, int8_t closed_slot) static
Definition at line 609 of file AsyncTCP.cpp.
{
  if (!pcb) {
    return ERR_CONN;
  }
  tcp_api_call_t msg;
  msg.pcb = pcb;
  msg.closed_slot = closed_slot;
  tcpip_api_call(_tcp_abort_api, (struct tcpip_api_call_data*)&msg);
  return msg.err;
}
References _tcp_abort_api(), tcp_api_call_t::closed_slot, tcp_api_call_t::err, and tcp_api_call_t::pcb.
Referenced by AsyncClient::abort(), and AsyncServer::end().
_tcp_abort_api()
err_t _tcp_abort_api (struct tcpip_api_call_data * api_call_msg) static
Definition at line 600 of file AsyncTCP.cpp.
{
  tcp_api_call_t* msg = (tcp_api_call_t*)api_call_msg;
  msg->err = ERR_CONN;
  if (msg->closed_slot == INVALID_CLOSED_SLOT || !_closed_slots[msg->closed_slot]) {
    tcp_abort(msg->pcb);
  }
  return msg->err;
}
References _closed_slots, tcp_api_call_t::closed_slot, tcp_api_call_t::err, INVALID_CLOSED_SLOT, and tcp_api_call_t::pcb.
Referenced by _tcp_abort().
_tcp_accept()
int8_t _tcp_accept (void * arg, AsyncClient * client) static
Definition at line 471 of file AsyncTCP.cpp.
{
  lwip_event_packet_t* e = (lwip_event_packet_t*)malloc(sizeof(lwip_event_packet_t));
  e->event = LWIP_TCP_ACCEPT;
  e->arg = arg;
  e->accept.client = client;
  if (!_prepend_async_event(&e)) {
    free((void*)(e));
  }
  return ERR_OK;
}
References _prepend_async_event(), lwip_event_packet_t::accept, lwip_event_packet_t::arg, lwip_event_packet_t::client, lwip_event_packet_t::event, and LWIP_TCP_ACCEPT.
Referenced by AsyncServer::_accept().
_tcp_bind()
esp_err_t _tcp_bind (tcp_pcb * pcb, ip_addr_t * addr, uint16_t port) static
Definition at line 646 of file AsyncTCP.cpp.
{
  if (!pcb) {
    return ESP_FAIL;
  }
  tcp_api_call_t msg;
  msg.pcb = pcb;
  msg.closed_slot = -1;
  msg.bind.addr = addr;
  msg.bind.port = port;
  tcpip_api_call(_tcp_bind_api, (struct tcpip_api_call_data*)&msg);
  return msg.err;
}
References _tcp_bind_api(), tcp_api_call_t::addr, tcp_api_call_t::bind, tcp_api_call_t::closed_slot, tcp_api_call_t::err, tcp_api_call_t::pcb, and tcp_api_call_t::port.
Referenced by AsyncServer::begin().
_tcp_bind_api()
err_t _tcp_bind_api (struct tcpip_api_call_data * api_call_msg) static
Definition at line 640 of file AsyncTCP.cpp.
{
  tcp_api_call_t* msg = (tcp_api_call_t*)api_call_msg;
  msg->err = tcp_bind(msg->pcb, msg->bind.addr, msg->bind.port);
  return msg->err;
}
References tcp_api_call_t::addr, tcp_api_call_t::bind, tcp_api_call_t::err, tcp_api_call_t::pcb, and tcp_api_call_t::port.
Referenced by _tcp_bind().
_tcp_clear_events()
int8_t _tcp_clear_events (void * arg) static
Definition at line 364 of file AsyncTCP.cpp.
{
  lwip_event_packet_t* e = (lwip_event_packet_t*)malloc(sizeof(lwip_event_packet_t));
  e->event = LWIP_TCP_CLEAR;
  e->arg = arg;
  if (!_prepend_async_event(&e)) {
    free((void*)(e));
  }
  return ERR_OK;
}
References _prepend_async_event(), lwip_event_packet_t::arg, lwip_event_packet_t::event, and LWIP_TCP_CLEAR.
Referenced by AsyncClient::_close(), and AsyncClient::_fin().
_tcp_close()
esp_err_t _tcp_close (tcp_pcb * pcb, int8_t closed_slot) static
Definition at line 589 of file AsyncTCP.cpp.
{
  if (!pcb) {
    return ERR_CONN;
  }
  tcp_api_call_t msg;
  msg.pcb = pcb;
  msg.closed_slot = closed_slot;
  tcpip_api_call(_tcp_close_api, (struct tcpip_api_call_data*)&msg);
  return msg.err;
}
References _tcp_close_api(), tcp_api_call_t::closed_slot, tcp_api_call_t::err, and tcp_api_call_t::pcb.
Referenced by AsyncClient::_close(), and AsyncServer::begin().
_tcp_close_api()
err_t _tcp_close_api (struct tcpip_api_call_data * api_call_msg) static
Definition at line 580 of file AsyncTCP.cpp.
{
  tcp_api_call_t* msg = (tcp_api_call_t*)api_call_msg;
  msg->err = ERR_CONN;
  if (msg->closed_slot == INVALID_CLOSED_SLOT || !_closed_slots[msg->closed_slot]) {
    msg->err = tcp_close(msg->pcb);
  }
  return msg->err;
}
References _closed_slots, tcp_api_call_t::closed_slot, tcp_api_call_t::err, INVALID_CLOSED_SLOT, and tcp_api_call_t::pcb.
Referenced by _tcp_close().
_tcp_connect()
esp_err_t _tcp_connect (tcp_pcb * pcb, int8_t closed_slot, ip_addr_t * addr, uint16_t port, tcp_connected_fn cb) static
Definition at line 626 of file AsyncTCP.cpp.
{
  if (!pcb) {
    return ESP_FAIL;
  }
  tcp_api_call_t msg;
  msg.pcb = pcb;
  msg.closed_slot = closed_slot;
  msg.connect.addr = addr;
  msg.connect.port = port;
  msg.connect.cb = cb;
  tcpip_api_call(_tcp_connect_api, (struct tcpip_api_call_data*)&msg);
  return msg.err;
}
References _tcp_connect_api(), tcp_api_call_t::addr, tcp_api_call_t::cb, tcp_api_call_t::closed_slot, tcp_api_call_t::connect, tcp_api_call_t::err, tcp_api_call_t::pcb, and tcp_api_call_t::port.
Referenced by AsyncClient::_connect().
_tcp_connect_api()
err_t _tcp_connect_api (struct tcpip_api_call_data * api_call_msg) static
Definition at line 620 of file AsyncTCP.cpp.
{
  tcp_api_call_t* msg = (tcp_api_call_t*)api_call_msg;
  msg->err = tcp_connect(msg->pcb, msg->connect.addr, msg->connect.port, msg->connect.cb);
  return msg->err;
}
References tcp_api_call_t::addr, tcp_api_call_t::cb, tcp_api_call_t::connect, tcp_api_call_t::err, tcp_api_call_t::pcb, and tcp_api_call_t::port.
Referenced by _tcp_connect().
_tcp_connected()
int8_t _tcp_connected (void * arg, tcp_pcb * pcb, int8_t err) static
Definition at line 374 of file AsyncTCP.cpp.
{
  // ets_printf("+C: 0x%08x\n", pcb);
  lwip_event_packet_t* e = (lwip_event_packet_t*)malloc(sizeof(lwip_event_packet_t));
  e->event = LWIP_TCP_CONNECTED;
  e->arg = arg;
  e->connected.pcb = pcb;
  e->connected.err = err;
  if (!_prepend_async_event(&e)) {
    free((void*)(e));
  }
  return ERR_OK;
}
References _prepend_async_event(), lwip_event_packet_t::arg, lwip_event_packet_t::connected, lwip_event_packet_t::err, lwip_event_packet_t::event, LWIP_TCP_CONNECTED, and lwip_event_packet_t::pcb.
Referenced by AsyncClient::_connect().
_tcp_dns_found()
void _tcp_dns_found (const char * name, struct ip_addr * ipaddr, void * arg) static
Definition at line 454 of file AsyncTCP.cpp.
{
  lwip_event_packet_t* e = (lwip_event_packet_t*)malloc(sizeof(lwip_event_packet_t));
  // ets_printf("+DNS: name=%s ipaddr=0x%08x arg=%x\n", name, ipaddr, arg);
  e->event = LWIP_TCP_DNS;
  e->arg = arg;
  e->dns.name = name;
  if (ipaddr) {
    memcpy(&e->dns.addr, ipaddr, sizeof(struct ip_addr));
  } else {
    memset(&e->dns.addr, 0, sizeof(e->dns.addr));
  }
  if (!_send_async_event(&e)) {
    free((void*)(e));
  }
}
References _send_async_event(), lwip_event_packet_t::addr, lwip_event_packet_t::arg, lwip_event_packet_t::dns, lwip_event_packet_t::event, LWIP_TCP_DNS, and lwip_event_packet_t::name.
Referenced by AsyncClient::connect().
_tcp_error()
void _tcp_error (void * arg, int8_t err) static
Definition at line 443 of file AsyncTCP.cpp.
{
  // ets_printf("+E: 0x%08x\n", arg);
  lwip_event_packet_t* e = (lwip_event_packet_t*)malloc(sizeof(lwip_event_packet_t));
  e->event = LWIP_TCP_ERROR;
  e->arg = arg;
  e->error.err = err;
  if (!_send_async_event(&e)) {
    free((void*)(e));
  }
}
References _send_async_event(), lwip_event_packet_t::arg, lwip_event_packet_t::err, lwip_event_packet_t::error, lwip_event_packet_t::event, and LWIP_TCP_ERROR.
Referenced by AsyncClient::_connect(), AsyncClient::AsyncClient(), and AsyncClient::operator=().
_tcp_listen_api()
err_t _tcp_listen_api (struct tcpip_api_call_data * api_call_msg) static
Definition at line 659 of file AsyncTCP.cpp.
{
  tcp_api_call_t* msg = (tcp_api_call_t*)api_call_msg;
  msg->err = 0;
  msg->pcb = tcp_listen_with_backlog(msg->pcb, msg->backlog);
  return msg->err;
}
References tcp_api_call_t::backlog, tcp_api_call_t::err, and tcp_api_call_t::pcb.
Referenced by _tcp_listen_with_backlog().
_tcp_listen_with_backlog()
tcp_pcb * _tcp_listen_with_backlog (tcp_pcb * pcb, uint8_t backlog) static
Definition at line 666 of file AsyncTCP.cpp.
{
  if (!pcb) {
    return NULL;
  }
  tcp_api_call_t msg;
  msg.pcb = pcb;
  msg.closed_slot = -1;
  msg.backlog = backlog ? backlog : 0xFF;
  tcpip_api_call(_tcp_listen_api, (struct tcpip_api_call_data*)&msg);
  return msg.pcb;
}
References _tcp_listen_api(), tcp_api_call_t::backlog, tcp_api_call_t::closed_slot, and tcp_api_call_t::pcb.
Referenced by AsyncServer::begin().
_tcp_output()
esp_err_t _tcp_output (tcp_pcb * pcb, int8_t closed_slot) static
Definition at line 522 of file AsyncTCP.cpp.
{
  if (!pcb) {
    return ERR_CONN;
  }
  tcp_api_call_t msg;
  msg.pcb = pcb;
  msg.closed_slot = closed_slot;
  tcpip_api_call(_tcp_output_api, (struct tcpip_api_call_data*)&msg);
  return msg.err;
}
References _tcp_output_api(), tcp_api_call_t::closed_slot, tcp_api_call_t::err, and tcp_api_call_t::pcb.
Referenced by AsyncClient::send().
_tcp_output_api()
err_t _tcp_output_api (struct tcpip_api_call_data * api_call_msg) static
Definition at line 513 of file AsyncTCP.cpp.
{
  tcp_api_call_t* msg = (tcp_api_call_t*)api_call_msg;
  msg->err = ERR_CONN;
  if (msg->closed_slot == INVALID_CLOSED_SLOT || !_closed_slots[msg->closed_slot]) {
    msg->err = tcp_output(msg->pcb);
  }
  return msg->err;
}
References _closed_slots, tcp_api_call_t::closed_slot, tcp_api_call_t::err, INVALID_CLOSED_SLOT, and tcp_api_call_t::pcb.
Referenced by _tcp_output().
_tcp_poll()
int8_t _tcp_poll (void * arg, struct tcp_pcb * pcb) static
Definition at line 387 of file AsyncTCP.cpp.
{
  // throttle polling events queing when event queue is getting filled up, let it handle _onack's
  // log_d("qs:%u", uxQueueMessagesWaiting(_async_queue));
  if (uxQueueMessagesWaiting(_async_queue) > (rand() % CONFIG_ASYNC_TCP_QUEUE_SIZE / 2 + CONFIG_ASYNC_TCP_QUEUE_SIZE / 4)) {
    log_d("throttling");
    return ERR_OK;
  }
  // ets_printf("+P: 0x%08x\n", pcb);
  lwip_event_packet_t* e = (lwip_event_packet_t*)malloc(sizeof(lwip_event_packet_t));
  e->event = LWIP_TCP_POLL;
  e->arg = arg;
  e->poll.pcb = pcb;
  // poll events are not critical 'cause those are repetitive, so we may not wait the queue in any case
  if (!_send_async_event(&e, 0)) {
    free((void*)(e));
  }
  return ERR_OK;
}
References _async_queue, _send_async_event(), lwip_event_packet_t::arg, CONFIG_ASYNC_TCP_QUEUE_SIZE, lwip_event_packet_t::event, LWIP_TCP_POLL, lwip_event_packet_t::pcb, and lwip_event_packet_t::poll.
Referenced by AsyncClient::_connect(), AsyncClient::AsyncClient(), and AsyncClient::operator=().
_tcp_recv()
int8_t _tcp_recv (void * arg, struct tcp_pcb * pcb, struct pbuf * pb, int8_t err) static
Definition at line 407 of file AsyncTCP.cpp.
{
  lwip_event_packet_t* e = (lwip_event_packet_t*)malloc(sizeof(lwip_event_packet_t));
  e->arg = arg;
  if (pb) {
    // ets_printf("+R: 0x%08x\n", pcb);
    e->event = LWIP_TCP_RECV;
    e->recv.pcb = pcb;
    e->recv.pb = pb;
    e->recv.err = err;
  } else {
    // ets_printf("+F: 0x%08x\n", pcb);
    e->event = LWIP_TCP_FIN;
    e->fin.pcb = pcb;
    e->fin.err = err;
    // close the PCB in LwIP thread
    AsyncClient::_s_lwip_fin(e->arg, e->fin.pcb, e->fin.err);
  }
  if (!_send_async_event(&e)) {
    free((void*)(e));
  }
  return ERR_OK;
}
References AsyncClient::_s_lwip_fin(), _send_async_event(), lwip_event_packet_t::arg, lwip_event_packet_t::err, lwip_event_packet_t::event, lwip_event_packet_t::fin, LWIP_TCP_FIN, LWIP_TCP_RECV, lwip_event_packet_t::pb, lwip_event_packet_t::pcb, and lwip_event_packet_t::recv.
Referenced by AsyncClient::_connect(), AsyncClient::AsyncClient(), and AsyncClient::operator=().
_tcp_recved()
esp_err_t _tcp_recved (tcp_pcb * pcb, int8_t closed_slot, size_t len) static
Definition at line 568 of file AsyncTCP.cpp.
{
  if (!pcb) {
    return ERR_CONN;
  }
  tcp_api_call_t msg;
  msg.pcb = pcb;
  msg.closed_slot = closed_slot;
  msg.received = len;
  tcpip_api_call(_tcp_recved_api, (struct tcpip_api_call_data*)&msg);
  return msg.err;
}
References _tcp_recved_api(), tcp_api_call_t::closed_slot, tcp_api_call_t::err, tcp_api_call_t::pcb, and tcp_api_call_t::received.
Referenced by AsyncClient::_recv(), AsyncClient::ack(), AsyncClient::ackPacket(), and AsyncClient::close().
_tcp_recved_api()
err_t _tcp_recved_api (struct tcpip_api_call_data * api_call_msg) static
Definition at line 556 of file AsyncTCP.cpp.
{
  tcp_api_call_t* msg = (tcp_api_call_t*)api_call_msg;
  msg->err = ERR_CONN;
  if (msg->closed_slot == INVALID_CLOSED_SLOT || !_closed_slots[msg->closed_slot]) {
    // if(msg->closed_slot != INVALID_CLOSED_SLOT && !_closed_slots[msg->closed_slot]) {
    // if(msg->closed_slot != INVALID_CLOSED_SLOT) {
    msg->err = 0;
    tcp_recved(msg->pcb, msg->received);
  }
  return msg->err;
}
References _closed_slots, tcp_api_call_t::closed_slot, tcp_api_call_t::err, INVALID_CLOSED_SLOT, tcp_api_call_t::pcb, and tcp_api_call_t::received.
Referenced by _tcp_recved().
_tcp_sent()
int8_t _tcp_sent (void * arg, struct tcp_pcb * pcb, uint16_t len) static
Definition at line 430 of file AsyncTCP.cpp.
{
  // ets_printf("+S: 0x%08x\n", pcb);
  lwip_event_packet_t* e = (lwip_event_packet_t*)malloc(sizeof(lwip_event_packet_t));
  e->event = LWIP_TCP_SENT;
  e->arg = arg;
  e->sent.pcb = pcb;
  e->sent.len = len;
  if (!_send_async_event(&e)) {
    free((void*)(e));
  }
  return ERR_OK;
}
References _send_async_event(), lwip_event_packet_t::arg, lwip_event_packet_t::event, lwip_event_packet_t::len, LWIP_TCP_SENT, lwip_event_packet_t::pcb, and lwip_event_packet_t::sent.
Referenced by AsyncClient::_connect(), AsyncClient::AsyncClient(), and AsyncClient::operator=().
_tcp_write()
esp_err_t _tcp_write (tcp_pcb * pcb, int8_t closed_slot, const char * data, size_t size, uint8_t apiflags) static
Definition at line 542 of file AsyncTCP.cpp.
{
  if (!pcb) {
    return ERR_CONN;
  }
  tcp_api_call_t msg;
  msg.pcb = pcb;
  msg.closed_slot = closed_slot;
  msg.write.data = data;
  msg.write.size = size;
  msg.write.apiflags = apiflags;
  tcpip_api_call(_tcp_write_api, (struct tcpip_api_call_data*)&msg);
  return msg.err;
}
References _tcp_write_api(), tcp_api_call_t::apiflags, tcp_api_call_t::closed_slot, tcp_api_call_t::data, tcp_api_call_t::err, tcp_api_call_t::pcb, tcp_api_call_t::size, and tcp_api_call_t::write.
Referenced by AsyncClient::add().
_tcp_write_api()
err_t _tcp_write_api (struct tcpip_api_call_data * api_call_msg) static
Definition at line 533 of file AsyncTCP.cpp.
{
  tcp_api_call_t* msg = (tcp_api_call_t*)api_call_msg;
  msg->err = ERR_CONN;
  if (msg->closed_slot == INVALID_CLOSED_SLOT || !_closed_slots[msg->closed_slot]) {
    msg->err = tcp_write(msg->pcb, msg->write.data, msg->write.size, msg->write.apiflags);
  }
  return msg->err;
}
References _closed_slots, tcp_api_call_t::apiflags, tcp_api_call_t::closed_slot, tcp_api_call_t::data, tcp_api_call_t::err, INVALID_CLOSED_SLOT, tcp_api_call_t::pcb, tcp_api_call_t::size, and tcp_api_call_t::write.
Referenced by _tcp_write().
customTaskCreateUniversal()
bool customTaskCreateUniversal (TaskFunction_t pxTaskCode, const char *const pcName, const uint32_t usStackDepth, void *const pvParameters, UBaseType_t uxPriority, TaskHandle_t *const pxCreatedTask, const BaseType_t xCoreID) static
Definition at line 328 of file AsyncTCP.cpp.
{
#ifndef CONFIG_FREERTOS_UNICORE
  if (xCoreID >= 0 && xCoreID < 2) {
    return xTaskCreatePinnedToCore(pxTaskCode, pcName, usStackDepth, pvParameters, uxPriority, pxCreatedTask, xCoreID);
  } else {
#endif
    return xTaskCreate(pxTaskCode, pcName, usStackDepth, pvParameters, uxPriority, pxCreatedTask);
#ifndef CONFIG_FREERTOS_UNICORE
  }
#endif
}
Referenced by _start_async_task().
Variable Documentation
_async_queue
QueueHandle_t _async_queue static
Definition at line 123 of file AsyncTCP.cpp.
Referenced by _get_async_event(), _init_async_event_queue(), _prepend_async_event(), _remove_events_with_arg(), _send_async_event(), and _tcp_poll().
_async_service_task_handle
TaskHandle_t _async_service_task_handle = NULL static
Definition at line 124 of file AsyncTCP.cpp.
Referenced by _async_service_task(), and _start_async_task().
_closed_index
uint32_t _closed_index static
Initial value:
                              = []() {
  _slots_lock = xSemaphoreCreateBinary();
  xSemaphoreGive(_slots_lock);
  for (int i = 0; i < _number_of_closed_slots; ++i) {
    _closed_slots[i] = 1;
  }
  return 1;
}()
Definition at line 129 of file AsyncTCP.cpp.
{
  _slots_lock = xSemaphoreCreateBinary();
  xSemaphoreGive(_slots_lock);
  for (int i = 0; i < _number_of_closed_slots; ++i) {
    _closed_slots[i] = 1;
  }
  return 1;
}();
Referenced by AsyncClient::_free_closed_slot().
_closed_slots
uint32_t _closed_slots[_number_of_closed_slots] static
Definition at line 128 of file AsyncTCP.cpp.
Referenced by AsyncClient::_allocate_closed_slot(), AsyncClient::_free_closed_slot(), _tcp_abort_api(), _tcp_close_api(), _tcp_output_api(), _tcp_recved_api(), and _tcp_write_api().
_number_of_closed_slots
const int _number_of_closed_slots = CONFIG_LWIP_MAX_ACTIVE_TCP
Definition at line 127 of file AsyncTCP.cpp.
Referenced by AsyncClient::_allocate_closed_slot().
_slots_lock
SemaphoreHandle_t _slots_lock
Definition at line 126 of file AsyncTCP.cpp.
Referenced by AsyncClient::_allocate_closed_slot(), and AsyncClient::_free_closed_slot().