ESP RFID Webui: TimerHandle.h File Reference
TimerHandle.h File Reference
#include <freertos/FreeRTOS.h>
#include <freertos/timers.h>
Functions
bool createServerCheckTimer (TimerCallbackFunction_t callback, TickType_t periodTicks)
bool createAuthSyncTimer (TimerCallbackFunction_t callback, TickType_t periodTicks)
bool createDisplayTimer (TimerCallbackFunction_t callback, TickType_t periodTicks)
void deleteServerCheckTimer ()
void deleteAuthSyncTimer ()
void deleteDisplayTimer ()
Variables
TimerHandle_t serverCheckTimer
TimerHandle_t authSyncTimer
TimerHandle_t displayTimer
Function Documentation
createAuthSyncTimer()
bool createAuthSyncTimer (TimerCallbackFunction_t callback, TickType_t periodTicks)
Definition at line 16 of file TimerHandle.cpp.
{
    if (authSyncTimer != nullptr) return true;
    authSyncTimer = xTimerCreate("AuthSync", periodTicks, pdTRUE, nullptr, callback);
    if (!authSyncTimer) return false;
    return xTimerStart(authSyncTimer, 0) == pdPASS;
}
References authSyncTimer.
Referenced by NetworkTask().
createDisplayTimer()
bool createDisplayTimer (TimerCallbackFunction_t callback, TickType_t periodTicks)
Definition at line 23 of file TimerHandle.cpp.
{
    if (displayTimer != nullptr) return true;
    displayTimer = xTimerCreate("Display", periodTicks, pdTRUE, nullptr, callback);
    if (!displayTimer) return false;
    return xTimerStart(displayTimer, 0) == pdPASS;
}
References displayTimer.
Referenced by setup().
createServerCheckTimer()
bool createServerCheckTimer (TimerCallbackFunction_t callback, TickType_t periodTicks)
Definition at line 9 of file TimerHandle.cpp.
{
    if (serverCheckTimer != nullptr) return true;
    serverCheckTimer = xTimerCreate("ServerCheck", periodTicks, pdTRUE, nullptr, callback);
    if (!serverCheckTimer) return false;
    return xTimerStart(serverCheckTimer, 0) == pdPASS;
}
References serverCheckTimer.
Referenced by NetworkTask().
deleteAuthSyncTimer()
void deleteAuthSyncTimer ()
Definition at line 37 of file TimerHandle.cpp.
{
    if (authSyncTimer) {
        xTimerStop(authSyncTimer, 0);
        xTimerDelete(authSyncTimer, 0);
        authSyncTimer = nullptr;
    }
}
References authSyncTimer.
deleteDisplayTimer()
void deleteDisplayTimer ()
Definition at line 44 of file TimerHandle.cpp.
{
    if (displayTimer) {
        xTimerStop(displayTimer, 0);
        xTimerDelete(displayTimer, 0);
        displayTimer = nullptr;
    }
}
References displayTimer.
deleteServerCheckTimer()
void deleteServerCheckTimer ()
Definition at line 30 of file TimerHandle.cpp.
{
    if (serverCheckTimer) {
        xTimerStop(serverCheckTimer, 0);
        xTimerDelete(serverCheckTimer, 0);
        serverCheckTimer = nullptr;
    }
}
References serverCheckTimer.
Variable Documentation
authSyncTimer
TimerHandle_t authSyncTimer extern
Definition at line 6 of file TimerHandle.cpp.
Referenced by createAuthSyncTimer(), and deleteAuthSyncTimer().
displayTimer
TimerHandle_t displayTimer extern
Definition at line 7 of file TimerHandle.cpp.
Referenced by createDisplayTimer(), and deleteDisplayTimer().
serverCheckTimer
TimerHandle_t serverCheckTimer extern
Definition at line 5 of file TimerHandle.cpp.
Referenced by createServerCheckTimer(), and deleteServerCheckTimer().