ESP RFID Webui: AsyncClient Class Reference
AsyncClient Class Reference
#include <AsyncTCP.h>
Public Member Functions
AsyncClient (tcp_pcb *pcb=0)
~AsyncClient ()
AsyncClient & operator= (const AsyncClient &other)
AsyncClient & operator+= (const AsyncClient &other)
bool operator== (const AsyncClient &other)
bool operator!= (const AsyncClient &other)
bool connect (const IPAddress &ip, uint16_t port)
bool connect (const IPv6Address &ip, uint16_t port)
bool connect (const char *host, uint16_t port)
void close (bool now=false)
close connection
void stop ()
int8_t abort ()
bool free ()
bool canSend ()
size_t space ()
size_t add (const char *data, size_t size, uint8_t apiflags=0x01)
add data to be send (but do not send yet)
bool send ()
send data previously add()'ed
size_t write (const char *data, size_t size, uint8_t apiflags=0x01)
add and enqueue data for sending
size_t write (const char *data)
add and enque data for sending
uint8_t state ()
bool connecting ()
bool connected ()
bool disconnecting ()
bool disconnected ()
bool freeable ()
uint16_t getMss ()
uint32_t getRxTimeout ()
void setRxTimeout (uint32_t timeout)
uint32_t getAckTimeout ()
void setAckTimeout (uint32_t timeout)
void setNoDelay (bool nodelay)
bool getNoDelay ()
void setKeepAlive (uint32_t ms, uint8_t cnt)
uint32_t getRemoteAddress ()
uint16_t getRemotePort ()
uint32_t getLocalAddress ()
uint16_t getLocalPort ()
IPAddress remoteIP ()
uint16_t remotePort ()
IPAddress localIP ()
uint16_t localPort ()
void onConnect (AcConnectHandler cb, void *arg=0)
void onDisconnect (AcConnectHandler cb, void *arg=0)
void onAck (AcAckHandler cb, void *arg=0)
void onError (AcErrorHandler cb, void *arg=0)
void onData (AcDataHandler cb, void *arg=0)
void onPacket (AcPacketHandler cb, void *arg=0)
void onTimeout (AcTimeoutHandler cb, void *arg=0)
void onPoll (AcConnectHandler cb, void *arg=0)
void ackPacket (struct pbuf *pb)
size_t ack (size_t len)
void ackLater ()
const char * stateToString ()
int8_t _recv (tcp_pcb *pcb, pbuf *pb, int8_t err)
tcp_pcb * pcb ()
Static Public Member Functions
static const char * errorToString (int8_t error)
static int8_t _s_poll (void *arg, struct tcp_pcb *tpcb)
static int8_t _s_recv (void *arg, struct tcp_pcb *tpcb, struct pbuf *pb, int8_t err)
static int8_t _s_fin (void *arg, struct tcp_pcb *tpcb, int8_t err)
static int8_t _s_lwip_fin (void *arg, struct tcp_pcb *tpcb, int8_t err)
static void _s_error (void *arg, int8_t err)
static int8_t _s_sent (void *arg, struct tcp_pcb *tpcb, uint16_t len)
static int8_t _s_connected (void *arg, struct tcp_pcb *tpcb, int8_t err)
static void _s_dns_found (const char *name, struct ip_addr *ipaddr, void *arg)
Data Fields
AsyncClient * prev
AsyncClient * next
Protected Member Functions
bool _connect (ip_addr_t addr, uint16_t port)
int8_t _close ()
void _free_closed_slot ()
bool _allocate_closed_slot ()
int8_t _connected (tcp_pcb *pcb, int8_t err)
void _error (int8_t err)
int8_t _poll (tcp_pcb *pcb)
int8_t _sent (tcp_pcb *pcb, uint16_t len)
int8_t _fin (tcp_pcb *pcb, int8_t err)
int8_t _lwip_fin (tcp_pcb *pcb, int8_t err)
void _dns_found (struct ip_addr *ipaddr)
Protected Attributes
tcp_pcb * _pcb
int8_t _closed_slot
AcConnectHandler _connect_cb
void * _connect_cb_arg
AcConnectHandler _discard_cb
void * _discard_cb_arg
AcAckHandler _sent_cb
void * _sent_cb_arg
AcErrorHandler _error_cb
void * _error_cb_arg
AcDataHandler _recv_cb
void * _recv_cb_arg
AcPacketHandler _pb_cb
void * _pb_cb_arg
AcTimeoutHandler _timeout_cb
void * _timeout_cb_arg
AcConnectHandler _poll_cb
void * _poll_cb_arg
bool _ack_pcb
uint32_t _tx_last_packet
uint32_t _rx_ack_len
uint32_t _rx_last_packet
uint32_t _rx_timeout
uint32_t _rx_last_ack
uint32_t _ack_timeout
uint16_t _connect_port
Detailed Description
Definition at line 94 of file AsyncTCP.h.
Constructor & Destructor Documentation
AsyncClient()
AsyncClient::AsyncClient (tcp_pcb * pcb = 0)
Definition at line 682 of file AsyncTCP.cpp.
    : _connect_cb(0), _connect_cb_arg(0), _discard_cb(0), _discard_cb_arg(0), _sent_cb(0), _sent_cb_arg(0), _error_cb(0), _error_cb_arg(0), _recv_cb(0), _recv_cb_arg(0), _pb_cb(0), _pb_cb_arg(0), _timeout_cb(0), _timeout_cb_arg(0), _ack_pcb(true), _tx_last_packet(0), _rx_timeout(0), _rx_last_ack(0), _ack_timeout(CONFIG_ASYNC_TCP_MAX_ACK_TIME), _connect_port(0), prev(NULL), next(NULL) {
  _pcb = pcb;
  _closed_slot = INVALID_CLOSED_SLOT;
  if (_pcb) {
    _rx_last_packet = millis();
    tcp_arg(_pcb, this);
    tcp_recv(_pcb, &_tcp_recv);
    tcp_sent(_pcb, &_tcp_sent);
    tcp_err(_pcb, &_tcp_error);
    tcp_poll(_pcb, &_tcp_poll, CONFIG_ASYNC_TCP_POLL_TIMER);
    if (!_allocate_closed_slot()) {
      _close();
    }
  }
}
References _ack_pcb, _ack_timeout, _allocate_closed_slot(), _close(), _closed_slot, _connect_cb, _connect_cb_arg, _connect_port, _discard_cb, _discard_cb_arg, _error_cb, _error_cb_arg, _pb_cb, _pb_cb_arg, _pcb, _recv_cb, _recv_cb_arg, _rx_last_ack, _rx_last_packet, _rx_timeout, _sent_cb, _sent_cb_arg, _tcp_error(), _tcp_poll(), _tcp_recv(), _tcp_sent(), _timeout_cb, _timeout_cb_arg, _tx_last_packet, CONFIG_ASYNC_TCP_MAX_ACK_TIME, CONFIG_ASYNC_TCP_POLL_TIMER, INVALID_CLOSED_SLOT, next, pcb(), and prev.
Referenced by _s_connected(), _s_dns_found(), _s_error(), _s_fin(), _s_lwip_fin(), _s_poll(), _s_recv(), _s_sent(), operator!=(), operator+=(), operator=(), and operator==().
~AsyncClient()
AsyncClient::~AsyncClient ()
Definition at line 699 of file AsyncTCP.cpp.
{
  if (_pcb) {
    _close();
  }
  _free_closed_slot();
}
References _close(), _free_closed_slot(), and _pcb.
Member Function Documentation
_allocate_closed_slot()
bool AsyncClient::_allocate_closed_slot () protected
Definition at line 977 of file AsyncTCP.cpp.
{
  if (_closed_slot != INVALID_CLOSED_SLOT) {
    return true;
  }
  xSemaphoreTake(_slots_lock, portMAX_DELAY);
  uint32_t closed_slot_min_index = 0;
  for (int i = 0; i < _number_of_closed_slots; ++i) {
    if ((_closed_slot == INVALID_CLOSED_SLOT || _closed_slots[i] <= closed_slot_min_index) && _closed_slots[i] != 0) {
      closed_slot_min_index = _closed_slots[i];
      _closed_slot = i;
    }
  }
  if (_closed_slot != INVALID_CLOSED_SLOT) {
    _closed_slots[_closed_slot] = 0;
  }
  xSemaphoreGive(_slots_lock);
  return (_closed_slot != INVALID_CLOSED_SLOT);
}
References _closed_slot, _closed_slots, _number_of_closed_slots, _slots_lock, and INVALID_CLOSED_SLOT.
Referenced by _connect(), and AsyncClient().
_close()
int8_t AsyncClient::_close () protected
Definition at line 952 of file AsyncTCP.cpp.
{
  // ets_printf("X: 0x%08x\n", (uint32_t)this);
  int8_t err = ERR_OK;
  if (_pcb) {
    TCP_MUTEX_LOCK();
    tcp_arg(_pcb, NULL);
    tcp_sent(_pcb, NULL);
    tcp_recv(_pcb, NULL);
    tcp_err(_pcb, NULL);
    tcp_poll(_pcb, NULL, 0);
    TCP_MUTEX_UNLOCK();
    _tcp_clear_events(this);
    err = _tcp_close(_pcb, _closed_slot);
    if (err != ERR_OK) {
      err = abort();
    }
    _free_closed_slot();
    _pcb = NULL;
    if (_discard_cb) {
      _discard_cb(_discard_cb_arg, this);
    }
  }
  return err;
}
References _closed_slot, _discard_cb, _discard_cb_arg, _free_closed_slot(), _pcb, _tcp_clear_events(), _tcp_close(), abort(), TCP_MUTEX_LOCK, and TCP_MUTEX_UNLOCK.
Referenced by _poll(), AsyncClient(), close(), operator=(), and ~AsyncClient().
_connect()
bool AsyncClient::_connect (ip_addr_t addr, uint16_t port) protected
Definition at line 795 of file AsyncTCP.cpp.
{
  if (_pcb) {
    log_d("already connected, state %d", _pcb->state);
    return false;
  }
  if (!_start_async_task()) {
    log_e("failed to start task");
    return false;
  }
  if (!_allocate_closed_slot()) {
    log_e("failed to allocate: closed slot full");
    return false;
  }
  TCP_MUTEX_LOCK();
  tcp_pcb* pcb = tcp_new_ip_type(addr.type);
  if (!pcb) {
    TCP_MUTEX_UNLOCK();
    log_e("pcb == NULL");
    return false;
  }
  tcp_arg(pcb, this);
  tcp_err(pcb, &_tcp_error);
  tcp_recv(pcb, &_tcp_recv);
  tcp_sent(pcb, &_tcp_sent);
  tcp_poll(pcb, &_tcp_poll, CONFIG_ASYNC_TCP_POLL_TIMER);
  TCP_MUTEX_UNLOCK();
  esp_err_t err = _tcp_connect(pcb, _closed_slot, &addr, port, (tcp_connected_fn)&_tcp_connected);
  return err == ESP_OK;
}
References _allocate_closed_slot(), _closed_slot, _pcb, _start_async_task(), _tcp_connect(), _tcp_connected(), _tcp_error(), _tcp_poll(), _tcp_recv(), _tcp_sent(), CONFIG_ASYNC_TCP_POLL_TIMER, pcb(), TCP_MUTEX_LOCK, and TCP_MUTEX_UNLOCK.
Referenced by connect(), and connect().
_connected()
int8_t AsyncClient::_connected (tcp_pcb * pcb, int8_t err) protected
Definition at line 1010 of file AsyncTCP.cpp.
{
  _pcb = reinterpret_cast<tcp_pcb*>(pcb);
  if (_pcb) {
    _rx_last_packet = millis();
  }
  if (_connect_cb) {
    _connect_cb(_connect_cb_arg, this);
  }
  return ERR_OK;
}
References _connect_cb, _connect_cb_arg, _pcb, _rx_last_packet, and pcb().
Referenced by _s_connected().
_dns_found()
void AsyncClient::_dns_found (struct ip_addr * ipaddr) protected
Definition at line 1142 of file AsyncTCP.cpp.
{
#if ESP_IDF_VERSION_MAJOR < 5
  if (ipaddr && IP_IS_V4(ipaddr)) {
    connect(IPAddress(ip_addr_get_ip4_u32(ipaddr)), _connect_port);
  #if LWIP_IPV6
  } else if (ipaddr && ipaddr->u_addr.ip6.addr) {
    connect(IPv6Address(ipaddr->u_addr.ip6.addr), _connect_port);
  #endif
#else
  if (ipaddr) {
    IPAddress ip;
    ip.from_ip_addr_t(ipaddr);
    connect(ip, _connect_port);
#endif
  } else {
    if (_error_cb) {
      _error_cb(_error_cb_arg, this, -55);
    }
    if (_discard_cb) {
      _discard_cb(_discard_cb_arg, this);
    }
  }
}
References _connect_port, _discard_cb, _discard_cb_arg, _error_cb, _error_cb_arg, and connect().
Referenced by _s_dns_found().
_error()
void AsyncClient::_error (int8_t err) protected
Definition at line 1021 of file AsyncTCP.cpp.
{
  if (_pcb) {
    TCP_MUTEX_LOCK();
    tcp_arg(_pcb, NULL);
    if (_pcb->state == LISTEN) {
      tcp_sent(_pcb, NULL);
      tcp_recv(_pcb, NULL);
      tcp_err(_pcb, NULL);
      tcp_poll(_pcb, NULL, 0);
    }
    TCP_MUTEX_UNLOCK();
    _free_closed_slot();
    _pcb = NULL;
  }
  if (_error_cb) {
    _error_cb(_error_cb_arg, this, err);
  }
  if (_discard_cb) {
    _discard_cb(_discard_cb_arg, this);
  }
}
References _discard_cb, _discard_cb_arg, _error_cb, _error_cb_arg, _free_closed_slot(), _pcb, TCP_MUTEX_LOCK, and TCP_MUTEX_UNLOCK.
Referenced by _s_error().
_fin()
int8_t AsyncClient::_fin (tcp_pcb * pcb, int8_t err) protected
Definition at line 1065 of file AsyncTCP.cpp.
{
  _tcp_clear_events(this);
  if (_discard_cb) {
    _discard_cb(_discard_cb_arg, this);
  }
  return ERR_OK;
}
References _discard_cb, _discard_cb_arg, _tcp_clear_events(), and pcb().
Referenced by _s_fin().
_free_closed_slot()
void AsyncClient::_free_closed_slot () protected
Definition at line 996 of file AsyncTCP.cpp.
{
  xSemaphoreTake(_slots_lock, portMAX_DELAY);
  if (_closed_slot != INVALID_CLOSED_SLOT) {
    _closed_slots[_closed_slot] = _closed_index;
    _closed_slot = INVALID_CLOSED_SLOT;
    ++_closed_index;
  }
  xSemaphoreGive(_slots_lock);
}
References _closed_index, _closed_slot, _closed_slots, _slots_lock, and INVALID_CLOSED_SLOT.
Referenced by _close(), _error(), _lwip_fin(), and ~AsyncClient().
_lwip_fin()
int8_t AsyncClient::_lwip_fin (tcp_pcb * pcb, int8_t err) protected
Definition at line 1044 of file AsyncTCP.cpp.
{
  if (!_pcb || pcb != _pcb) {
    log_d("0x%08x != 0x%08x", (uint32_t)pcb, (uint32_t)_pcb);
    return ERR_OK;
  }
  tcp_arg(_pcb, NULL);
  if (_pcb->state == LISTEN) {
    tcp_sent(_pcb, NULL);
    tcp_recv(_pcb, NULL);
    tcp_err(_pcb, NULL);
    tcp_poll(_pcb, NULL, 0);
  }
  if (tcp_close(_pcb) != ERR_OK) {
    tcp_abort(_pcb);
  }
  _free_closed_slot();
  _pcb = NULL;
  return ERR_OK;
}
References _free_closed_slot(), _pcb, and pcb().
Referenced by _s_lwip_fin().
_poll()
int8_t AsyncClient::_poll (tcp_pcb * pcb) protected
Definition at line 1106 of file AsyncTCP.cpp.
{
  if (!_pcb) {
    // log_d("pcb is NULL");
    return ERR_OK;
  }
  if (pcb != _pcb) {
    log_d("0x%08x != 0x%08x", (uint32_t)pcb, (uint32_t)_pcb);
    return ERR_OK;
  }
  uint32_t now = millis();
  // ACK Timeout
  if (_ack_timeout) {
    const uint32_t one_day = 86400000;
    bool last_tx_is_after_last_ack = (_rx_last_ack - _tx_last_packet + one_day) < one_day;
    if (last_tx_is_after_last_ack && (now - _tx_last_packet) >= _ack_timeout) {
      log_d("ack timeout %d", pcb->state);
      if (_timeout_cb)
        _timeout_cb(_timeout_cb_arg, this, (now - _tx_last_packet));
      return ERR_OK;
    }
  }
  // RX Timeout
  if (_rx_timeout && (now - _rx_last_packet) >= (_rx_timeout * 1000)) {
    log_d("rx timeout %d", pcb->state);
    _close();
    return ERR_OK;
  }
  // Everything is fine
  if (_poll_cb) {
    _poll_cb(_poll_cb_arg, this);
  }
  return ERR_OK;
}
References _ack_timeout, _close(), _pcb, _poll_cb, _poll_cb_arg, _rx_last_ack, _rx_last_packet, _rx_timeout, _timeout_cb, _timeout_cb_arg, _tx_last_packet, and pcb().
Referenced by _s_poll().
_recv()
int8_t AsyncClient::_recv (tcp_pcb * pcb, pbuf * pb, int8_t err)
Definition at line 1081 of file AsyncTCP.cpp.
{
  while (pb != NULL) {
    _rx_last_packet = millis();
    // we should not ack before we assimilate the data
    _ack_pcb = true;
    pbuf* b = pb;
    pb = b->next;
    b->next = NULL;
    if (_pb_cb) {
      _pb_cb(_pb_cb_arg, this, b);
    } else {
      if (_recv_cb) {
        _recv_cb(_recv_cb_arg, this, b->payload, b->len);
      }
      if (!_ack_pcb) {
        _rx_ack_len += b->len;
      } else if (_pcb) {
        _tcp_recved(_pcb, _closed_slot, b->len);
      }
    }
    pbuf_free(b);
  }
  return ERR_OK;
}
References _ack_pcb, _closed_slot, _pb_cb, _pb_cb_arg, _pcb, _recv_cb, _recv_cb_arg, _rx_ack_len, _rx_last_packet, _tcp_recved(), and pcb().
Referenced by _s_recv().
_s_connected()
int8_t AsyncClient::_s_connected (void * arg, struct tcp_pcb * tpcb, int8_t err) static
Definition at line 1506 of file AsyncTCP.cpp.
{
  return reinterpret_cast<AsyncClient*>(arg)->_connected(pcb, err);
}
References _connected(), AsyncClient(), and pcb().
Referenced by _handle_async_event().
_s_dns_found()
void AsyncClient::_s_dns_found (const char * name, struct ip_addr * ipaddr, void * arg) static
Definition at line 1478 of file AsyncTCP.cpp.
{
  reinterpret_cast<AsyncClient*>(arg)->_dns_found(ipaddr);
}
References _dns_found(), and AsyncClient().
Referenced by _handle_async_event().
_s_error()
void AsyncClient::_s_error (void * arg, int8_t err) static
Definition at line 1502 of file AsyncTCP.cpp.
{
  reinterpret_cast<AsyncClient*>(arg)->_error(err);
}
References _error(), and AsyncClient().
Referenced by _handle_async_event().
_s_fin()
int8_t AsyncClient::_s_fin (void * arg, struct tcp_pcb * tpcb, int8_t err) static
Definition at line 1490 of file AsyncTCP.cpp.
{
  return reinterpret_cast<AsyncClient*>(arg)->_fin(pcb, err);
}
References _fin(), AsyncClient(), and pcb().
Referenced by _handle_async_event().
_s_lwip_fin()
int8_t AsyncClient::_s_lwip_fin (void * arg, struct tcp_pcb * tpcb, int8_t err) static
Definition at line 1494 of file AsyncTCP.cpp.
{
  return reinterpret_cast<AsyncClient*>(arg)->_lwip_fin(pcb, err);
}
References _lwip_fin(), AsyncClient(), and pcb().
Referenced by _tcp_recv().
_s_poll()
int8_t AsyncClient::_s_poll (void * arg, struct tcp_pcb * tpcb) static
Definition at line 1482 of file AsyncTCP.cpp.
{
  return reinterpret_cast<AsyncClient*>(arg)->_poll(pcb);
}
References _poll(), AsyncClient(), and pcb().
Referenced by _handle_async_event().
_s_recv()
int8_t AsyncClient::_s_recv (void * arg, struct tcp_pcb * tpcb, struct pbuf * pb, int8_t err) static
Definition at line 1486 of file AsyncTCP.cpp.
{
  return reinterpret_cast<AsyncClient*>(arg)->_recv(pcb, pb, err);
}
References _recv(), AsyncClient(), and pcb().
Referenced by _handle_async_event().
_s_sent()
int8_t AsyncClient::_s_sent (void * arg, struct tcp_pcb * tpcb, uint16_t len) static
Definition at line 1498 of file AsyncTCP.cpp.
{
  return reinterpret_cast<AsyncClient*>(arg)->_sent(pcb, len);
}
References _sent(), AsyncClient(), and pcb().
Referenced by _handle_async_event().
_sent()
int8_t AsyncClient::_sent (tcp_pcb * pcb, uint16_t len) protected
Definition at line 1073 of file AsyncTCP.cpp.
{
  _rx_last_ack = _rx_last_packet = millis();
  if (_sent_cb) {
    _sent_cb(_sent_cb_arg, this, len, (_rx_last_packet - _tx_last_packet));
  }
  return ERR_OK;
}
References _rx_last_ack, _rx_last_packet, _sent_cb, _sent_cb_arg, _tx_last_packet, and pcb().
Referenced by _s_sent().
abort()
int8_t AsyncClient::abort ()
Definition at line 888 of file AsyncTCP.cpp.
{
  if (_pcb) {
    _tcp_abort(_pcb, _closed_slot);
    _pcb = NULL;
  }
  return ERR_ABRT;
}
References _closed_slot, _pcb, and _tcp_abort().
Referenced by _close().
ack()
size_t AsyncClient::ack (size_t len)
Definition at line 930 of file AsyncTCP.cpp.
{
  if (len > _rx_ack_len)
    len = _rx_ack_len;
  if (len) {
    _tcp_recved(_pcb, _closed_slot, len);
  }
  _rx_ack_len -= len;
  return len;
}
References _closed_slot, _pcb, _rx_ack_len, and _tcp_recved().
ackLater()
void AsyncClient::ackLater () inline
Definition at line 242 of file AsyncTCP.h.
{ _ack_pcb = false; }
References _ack_pcb.
ackPacket()
void AsyncClient::ackPacket (struct pbuf * pb)
Definition at line 940 of file AsyncTCP.cpp.
{
  if (!pb) {
    return;
  }
  _tcp_recved(_pcb, _closed_slot, pb->len);
  pbuf_free(pb);
}
References _closed_slot, _pcb, and _tcp_recved().
add()
size_t AsyncClient::add (const char * data, size_t size, uint8_t apiflags = 0x01)
add data to be send (but do not send yet)
Note
add() would call lwip's tcp_write() By default apiflags=ASYNC_WRITE_FLAG_COPY You could try to use apiflags with this flag unset to pass data by reference and avoid copy to socket buffer, but looks like it does not work for Arduino's lwip in ESP32/IDF at least it is enforced in https://github.com/espressif/esp-lwip/blob/0606eed9d8b98a797514fdf6eabb4daf1c8c8cd9/src/core/tcp_out.c#L422C5-L422C30 if LWIP_NETIF_TX_SINGLE_PBUF is set, and it is set indeed in IDF https://github.com/espressif/esp-idf/blob/a0f798cfc4bbd624aab52b2c194d219e242d80c1/components/lwip/port/include/lwipopts.h#L744
Parameters
data
size
apiflags
Returns
size_t amount of data that has been copied
Definition at line 903 of file AsyncTCP.cpp.
{
  if (!_pcb || size == 0 || data == NULL) {
    return 0;
  }
  size_t room = space();
  if (!room) {
    return 0;
  }
  size_t will_send = (room < size) ? room : size;
  int8_t err = ERR_OK;
  err = _tcp_write(_pcb, _closed_slot, data, will_send, apiflags);
  if (err != ERR_OK) {
    return 0;
  }
  return will_send;
}
References _closed_slot, _pcb, _tcp_write(), and space().
Referenced by write().
canSend()
bool AsyncClient::canSend ()
Definition at line 1400 of file AsyncTCP.cpp.
{
  return space() > 0;
}
References space().
close()
void AsyncClient::close (bool now = false)
close connection
Parameters
now - ignored
Definition at line 881 of file AsyncTCP.cpp.
{
  if (_pcb) {
    _tcp_recved(_pcb, _closed_slot, _rx_ack_len);
  }
  _close();
}
References _close(), _closed_slot, _pcb, _rx_ack_len, and _tcp_recved().
Referenced by AsyncTelnet::begin(), AsyncTelnetSerial::begin(), and stop().
connect() [1/3]
bool AsyncClient::connect (const char * host, uint16_t port)
Definition at line 849 of file AsyncTCP.cpp.
{
  ip_addr_t addr;
  if (!_start_async_task()) {
    log_e("failed to start task");
    return false;
  }
  TCP_MUTEX_LOCK();
  err_t err = dns_gethostbyname(host, &addr, (dns_found_callback)&_tcp_dns_found, this);
  TCP_MUTEX_UNLOCK();
  if (err == ERR_OK) {
#if ESP_IDF_VERSION_MAJOR < 5
  #if LWIP_IPV6
    if (addr.type == IPADDR_TYPE_V6) {
      return connect(IPv6Address(addr.u_addr.ip6.addr), port);
    }
    return connect(IPAddress(addr.u_addr.ip4.addr), port);
  #else
    return connect(IPAddress(addr.addr), port);
  #endif
#else
    return _connect(addr, port);
#endif
  } else if (err == ERR_INPROGRESS) {
    _connect_port = port;
    return true;
  }
  log_d("error: %d", err);
  return false;
}
References _connect(), _connect_port, _start_async_task(), _tcp_dns_found(), connect(), TCP_MUTEX_LOCK, and TCP_MUTEX_UNLOCK.
connect() [2/3]
bool AsyncClient::connect (const IPAddress & ip, uint16_t port)
Definition at line 828 of file AsyncTCP.cpp.
{
  ip_addr_t addr;
#if ESP_IDF_VERSION_MAJOR < 5
  addr.u_addr.ip4.addr = ip;
  addr.type = IPADDR_TYPE_V4;
#else
  ip.to_ip_addr_t(&addr);
#endif
  return _connect(addr, port);
}
References _connect().
Referenced by _dns_found(), and connect().
connect() [3/3]
bool AsyncClient::connect (const IPv6Address & ip, uint16_t port)
connected()
bool AsyncClient::connected ()
Definition at line 1365 of file AsyncTCP.cpp.
{
  if (!_pcb) {
    return false;
  }
  return _pcb->state == ESTABLISHED;
}
References _pcb.
Referenced by AsyncTelnet::isClientConnected().
connecting()
bool AsyncClient::connecting ()
Definition at line 1372 of file AsyncTCP.cpp.
{
  if (!_pcb) {
    return false;
  }
  return _pcb->state > CLOSED && _pcb->state < ESTABLISHED;
}
References _pcb.
disconnected()
bool AsyncClient::disconnected ()
Definition at line 1386 of file AsyncTCP.cpp.
{
  if (!_pcb) {
    return true;
  }
  return _pcb->state == CLOSED || _pcb->state == TIME_WAIT;
}
References _pcb.
disconnecting()
bool AsyncClient::disconnecting ()
Definition at line 1379 of file AsyncTCP.cpp.
{
  if (!_pcb) {
    return false;
  }
  return _pcb->state > ESTABLISHED && _pcb->state < TIME_WAIT;
}
References _pcb.
errorToString()
const char * AsyncClient::errorToString (int8_t error) static
Definition at line 1404 of file AsyncTCP.cpp.
{
  switch (error) {
    case ERR_OK:
      return "OK";
    case ERR_MEM:
      return "Out of memory error";
    case ERR_BUF:
      return "Buffer error";
    case ERR_TIMEOUT:
      return "Timeout";
    case ERR_RTE:
      return "Routing problem";
    case ERR_INPROGRESS:
      return "Operation in progress";
    case ERR_VAL:
      return "Illegal value";
    case ERR_WOULDBLOCK:
      return "Operation would block";
    case ERR_USE:
      return "Address in use";
    case ERR_ALREADY:
      return "Already connected";
    case ERR_CONN:
      return "Not connected";
    case ERR_IF:
      return "Low-level netif error";
    case ERR_ABRT:
      return "Connection aborted";
    case ERR_RST:
      return "Connection reset";
    case ERR_CLSD:
      return "Connection closed";
    case ERR_ARG:
      return "Illegal argument";
    case -55:
      return "DNS failed";
    default:
      return "UNKNOWN";
  }
}
free()
bool AsyncClient::free ()
Definition at line 1170 of file AsyncTCP.cpp.
                       {
  if (!_pcb) {
    return true;
  }
  if (_pcb->state == CLOSED || _pcb->state > ESTABLISHED) {
    return true;
  }
  return false;
}
References _pcb.
Referenced by AsyncTelnet::begin(), and AsyncTelnetSerial::begin().
freeable()
bool AsyncClient::freeable ()
Definition at line 1393 of file AsyncTCP.cpp.
{
  if (!_pcb) {
    return true;
  }
  return _pcb->state == CLOSED || _pcb->state > ESTABLISHED;
}
References _pcb.
getAckTimeout()
uint32_t AsyncClient::getAckTimeout ()
Definition at line 1196 of file AsyncTCP.cpp.
{
  return _ack_timeout;
}
References _ack_timeout.
getLocalAddress()
uint32_t AsyncClient::getLocalAddress ()
Definition at line 1306 of file AsyncTCP.cpp.
{
  if (!_pcb) {
    return 0;
  }
#if LWIP_IPV4 && LWIP_IPV6
  return _pcb->local_ip.u_addr.ip4.addr;
#else
  return _pcb->local_ip.addr;
#endif
}
References _pcb.
Referenced by localIP().
getLocalPort()
uint16_t AsyncClient::getLocalPort ()
Definition at line 1317 of file AsyncTCP.cpp.
{
  if (!_pcb) {
    return 0;
  }
  return _pcb->local_port;
}
References _pcb.
Referenced by localPort().
getMss()
uint16_t AsyncClient::getMss ()
Definition at line 1234 of file AsyncTCP.cpp.
{
  if (!_pcb) {
    return 0;
  }
  return tcp_mss(_pcb);
}
References _pcb.
getNoDelay()
bool AsyncClient::getNoDelay ()
Definition at line 1215 of file AsyncTCP.cpp.
{
  if (!_pcb) {
    return false;
  }
  return tcp_nagle_disabled(_pcb);
}
References _pcb.
getRemoteAddress()
uint32_t AsyncClient::getRemoteAddress ()
Definition at line 1241 of file AsyncTCP.cpp.
{
  if (!_pcb) {
    return 0;
  }
#if LWIP_IPV4 && LWIP_IPV6
  return _pcb->remote_ip.u_addr.ip4.addr;
#else
  return _pcb->remote_ip.addr;
#endif
}
References _pcb.
Referenced by remoteIP().
getRemotePort()
uint16_t AsyncClient::getRemotePort ()
Definition at line 1299 of file AsyncTCP.cpp.
{
  if (!_pcb) {
    return 0;
  }
  return _pcb->remote_port;
}
References _pcb.
Referenced by remotePort().
getRxTimeout()
uint32_t AsyncClient::getRxTimeout ()
Definition at line 1192 of file AsyncTCP.cpp.
{
  return _rx_timeout;
}
References _rx_timeout.
localIP()
IPAddress AsyncClient::localIP ()
Definition at line 1341 of file AsyncTCP.cpp.
{
#if ESP_IDF_VERSION_MAJOR < 5
  return IPAddress(getLocalAddress());
#else
  if (!_pcb) {
    return IPAddress();
  }
  IPAddress ip;
  ip.from_ip_addr_t(&(_pcb->local_ip));
  return ip;
#endif
}
References _pcb, and getLocalAddress().
localPort()
uint16_t AsyncClient::localPort ()
Definition at line 1354 of file AsyncTCP.cpp.
{
  return getLocalPort();
}
References getLocalPort().
onAck()
void AsyncClient::onAck (AcAckHandler cb, void * arg = 0)
Definition at line 761 of file AsyncTCP.cpp.
{
  _sent_cb = cb;
  _sent_cb_arg = arg;
}
References _sent_cb, and _sent_cb_arg.
onConnect()
void AsyncClient::onConnect (AcConnectHandler cb, void * arg = 0)
Definition at line 751 of file AsyncTCP.cpp.
{
  _connect_cb = cb;
  _connect_cb_arg = arg;
}
References _connect_cb, and _connect_cb_arg.
onData()
void AsyncClient::onData (AcDataHandler cb, void * arg = 0)
Definition at line 771 of file AsyncTCP.cpp.
{
  _recv_cb = cb;
  _recv_cb_arg = arg;
}
References _recv_cb, and _recv_cb_arg.
Referenced by AsyncTelnet::begin(), and AsyncTelnetSerial::begin().
onDisconnect()
void AsyncClient::onDisconnect (AcConnectHandler cb, void * arg = 0)
Definition at line 756 of file AsyncTCP.cpp.
{
  _discard_cb = cb;
  _discard_cb_arg = arg;
}
References _discard_cb, and _discard_cb_arg.
Referenced by AsyncTelnet::begin(), and AsyncTelnetSerial::begin().
onError()
void AsyncClient::onError (AcErrorHandler cb, void * arg = 0)
Definition at line 766 of file AsyncTCP.cpp.
{
  _error_cb = cb;
  _error_cb_arg = arg;
}
References _error_cb, and _error_cb_arg.
onPacket()
void AsyncClient::onPacket (AcPacketHandler cb, void * arg = 0)
Definition at line 776 of file AsyncTCP.cpp.
{
  _pb_cb = cb;
  _pb_cb_arg = arg;
}
References _pb_cb, and _pb_cb_arg.
onPoll()
void AsyncClient::onPoll (AcConnectHandler cb, void * arg = 0)
Definition at line 786 of file AsyncTCP.cpp.
{
  _poll_cb = cb;
  _poll_cb_arg = arg;
}
References _poll_cb, and _poll_cb_arg.
onTimeout()
void AsyncClient::onTimeout (AcTimeoutHandler cb, void * arg = 0)
Definition at line 781 of file AsyncTCP.cpp.
{
  _timeout_cb = cb;
  _timeout_cb_arg = arg;
}
References _timeout_cb, and _timeout_cb_arg.
operator!=()
bool AsyncClient::operator!= (const AsyncClient & other) inline
Definition at line 104 of file AsyncTCP.h.
{
      return !(*this == other);
    }
References AsyncClient().
operator+=()
AsyncClient & AsyncClient::operator+= (const AsyncClient & other)
Definition at line 732 of file AsyncTCP.cpp.
{
  if (next == NULL) {
    next = (AsyncClient*)(&other);
    next->prev = this;
  } else {
    AsyncClient* c = next;
    while (c->next != NULL) {
      c = c->next;
    }
    c->next = (AsyncClient*)(&other);
    c->next->prev = c;
  }
  return *this;
}
References AsyncClient(), next, and prev.
operator=()
AsyncClient & AsyncClient::operator= (const AsyncClient & other)
Definition at line 710 of file AsyncTCP.cpp.
{
  if (_pcb) {
    _close();
  }
  _pcb = other._pcb;
  _closed_slot = other._closed_slot;
  if (_pcb) {
    _rx_last_packet = millis();
    tcp_arg(_pcb, this);
    tcp_recv(_pcb, &_tcp_recv);
    tcp_sent(_pcb, &_tcp_sent);
    tcp_err(_pcb, &_tcp_error);
    tcp_poll(_pcb, &_tcp_poll, CONFIG_ASYNC_TCP_POLL_TIMER);
  }
  return *this;
}
References _close(), _closed_slot, _pcb, _rx_last_packet, _tcp_error(), _tcp_poll(), _tcp_recv(), _tcp_sent(), AsyncClient(), and CONFIG_ASYNC_TCP_POLL_TIMER.
operator==()
bool AsyncClient::operator== (const AsyncClient & other)
Definition at line 728 of file AsyncTCP.cpp.
{
  return _pcb == other._pcb;
}
References _pcb, and AsyncClient().
pcb()
tcp_pcb * AsyncClient::pcb () inline
Definition at line 258 of file AsyncTCP.h.
{ return _pcb; }
References _pcb.
Referenced by _connect(), _connected(), _fin(), _lwip_fin(), _poll(), _recv(), _s_connected(), _s_fin(), _s_lwip_fin(), _s_poll(), _s_recv(), _s_sent(), _sent(), and AsyncClient().
remoteIP()
IPAddress AsyncClient::remoteIP ()
Definition at line 1324 of file AsyncTCP.cpp.
{
#if ESP_IDF_VERSION_MAJOR < 5
  return IPAddress(getRemoteAddress());
#else
  if (!_pcb) {
    return IPAddress();
  }
  IPAddress ip;
  ip.from_ip_addr_t(&(_pcb->remote_ip));
  return ip;
#endif
}
References _pcb, and getRemoteAddress().
remotePort()
uint16_t AsyncClient::remotePort ()
Definition at line 1337 of file AsyncTCP.cpp.
{
  return getRemotePort();
}
References getRemotePort().
send()
bool AsyncClient::send ()
send data previously add()'ed
Returns
true on success
false on error
Definition at line 920 of file AsyncTCP.cpp.
                       {
  auto backup = _tx_last_packet;
  _tx_last_packet = millis();
  if (_tcp_output(_pcb, _closed_slot) == ERR_OK) {
    return true;
  }
  _tx_last_packet = backup;
  return false;
}
References _closed_slot, _pcb, _tcp_output(), and _tx_last_packet.
Referenced by write().
setAckTimeout()
void AsyncClient::setAckTimeout (uint32_t timeout)
Definition at line 1200 of file AsyncTCP.cpp.
{
  _ack_timeout = timeout;
}
References _ack_timeout.
setKeepAlive()
void AsyncClient::setKeepAlive (uint32_t ms, uint8_t cnt)
Definition at line 1222 of file AsyncTCP.cpp.
{
  if (ms != 0) {
    _pcb->so_options |= SOF_KEEPALIVE; // Turn on TCP Keepalive for the given pcb
    // Set the time between keepalive messages in milli-seconds
    _pcb->keep_idle = ms;
    _pcb->keep_intvl = ms;
    _pcb->keep_cnt = cnt; // The number of unanswered probes required to force closure of the socket
  } else {
    _pcb->so_options &= ~SOF_KEEPALIVE; // Turn off TCP Keepalive for the given pcb
  }
}
References _pcb.
setNoDelay()
void AsyncClient::setNoDelay (bool nodelay)
Definition at line 1204 of file AsyncTCP.cpp.
{
  if (!_pcb) {
    return;
  }
  if (nodelay) {
    tcp_nagle_disable(_pcb);
  } else {
    tcp_nagle_enable(_pcb);
  }
}
References _pcb.
Referenced by AsyncServer::_accept().
setRxTimeout()
void AsyncClient::setRxTimeout (uint32_t timeout)
Definition at line 1188 of file AsyncTCP.cpp.
{
  _rx_timeout = timeout;
}
References _rx_timeout.
space()
size_t AsyncClient::space ()
Definition at line 896 of file AsyncTCP.cpp.
{
  if ((_pcb != NULL) && (_pcb->state == ESTABLISHED)) {
    return tcp_sndbuf(_pcb);
  }
  return 0;
}
References _pcb.
Referenced by add(), and canSend().
state()
uint8_t AsyncClient::state ()
Definition at line 1358 of file AsyncTCP.cpp.
{
  if (!_pcb) {
    return 0;
  }
  return _pcb->state;
}
References _pcb.
Referenced by stateToString().
stateToString()
const char * AsyncClient::stateToString ()
Definition at line 1445 of file AsyncTCP.cpp.
{
  switch (state()) {
    case 0:
      return "Closed";
    case 1:
      return "Listen";
    case 2:
      return "SYN Sent";
    case 3:
      return "SYN Received";
    case 4:
      return "Established";
    case 5:
      return "FIN Wait 1";
    case 6:
      return "FIN Wait 2";
    case 7:
      return "Close Wait";
    case 8:
      return "Closing";
    case 9:
      return "Last ACK";
    case 10:
      return "Time Wait";
    default:
      return "UNKNOWN";
  }
}
References state().
stop()
void AsyncClient::stop () inline
Definition at line 119 of file AsyncTCP.h.
{ close(false); };
References close().
write() [1/2]
size_t AsyncClient::write (const char * data) inline
add and enque data for sending
Note
treats data as null-terminated string
Parameters
data
Returns
size_t
Definition at line 172 of file AsyncTCP.h.
{ return data == NULL ? 0 : write(data, strlen(data)); };
References write().
Referenced by write().
write() [2/2]
size_t AsyncClient::write (const char * data, size_t size, uint8_t apiflags = 0x01)
add and enqueue data for sending
Note
it is same as add() + send()
only make sense when canSend() == true
Parameters
data
size
apiflags
Returns
size_t
Definition at line 1180 of file AsyncTCP.cpp.
{
  size_t will_send = add(data, size, apiflags);
  if (!will_send || !send()) {
    return 0;
  }
  return will_send;
}
References add(), and send().
Field Documentation
_ack_pcb
bool AsyncClient::_ack_pcb protected
Definition at line 283 of file AsyncTCP.h.
Referenced by _recv(), ackLater(), and AsyncClient().
_ack_timeout
uint32_t AsyncClient::_ack_timeout protected
Definition at line 289 of file AsyncTCP.h.
Referenced by _poll(), AsyncClient(), getAckTimeout(), and setAckTimeout().
_closed_slot
int8_t AsyncClient::_closed_slot protected
Definition at line 264 of file AsyncTCP.h.
Referenced by _allocate_closed_slot(), _close(), _connect(), _free_closed_slot(), _recv(), abort(), ack(), ackPacket(), add(), AsyncClient(), close(), operator=(), and send().
_connect_cb
AcConnectHandler AsyncClient::_connect_cb protected
Definition at line 266 of file AsyncTCP.h.
Referenced by _connected(), AsyncClient(), and onConnect().
_connect_cb_arg
void* AsyncClient::_connect_cb_arg protected
Definition at line 267 of file AsyncTCP.h.
Referenced by _connected(), AsyncClient(), and onConnect().
_connect_port
uint16_t AsyncClient::_connect_port protected
Definition at line 290 of file AsyncTCP.h.
Referenced by _dns_found(), AsyncClient(), and connect().
_discard_cb
AcConnectHandler AsyncClient::_discard_cb protected
Definition at line 268 of file AsyncTCP.h.
Referenced by _close(), _dns_found(), _error(), _fin(), AsyncClient(), and onDisconnect().
_discard_cb_arg
void* AsyncClient::_discard_cb_arg protected
Definition at line 269 of file AsyncTCP.h.
Referenced by _close(), _dns_found(), _error(), _fin(), AsyncClient(), and onDisconnect().
_error_cb
AcErrorHandler AsyncClient::_error_cb protected
Definition at line 272 of file AsyncTCP.h.
Referenced by _dns_found(), _error(), AsyncClient(), and onError().
_error_cb_arg
void* AsyncClient::_error_cb_arg protected
Definition at line 273 of file AsyncTCP.h.
Referenced by _dns_found(), _error(), AsyncClient(), and onError().
_pb_cb
AcPacketHandler AsyncClient::_pb_cb protected
Definition at line 276 of file AsyncTCP.h.
Referenced by _recv(), AsyncClient(), and onPacket().
_pb_cb_arg
void* AsyncClient::_pb_cb_arg protected
Definition at line 277 of file AsyncTCP.h.
Referenced by _recv(), AsyncClient(), and onPacket().
_pcb
tcp_pcb* AsyncClient::_pcb protected
Definition at line 263 of file AsyncTCP.h.
Referenced by _close(), _connect(), _connected(), _error(), _lwip_fin(), _poll(), _recv(), abort(), ack(), ackPacket(), add(), AsyncClient(), close(), connected(), connecting(), disconnected(), disconnecting(), free(), freeable(), getLocalAddress(), getLocalPort(), getMss(), getNoDelay(), getRemoteAddress(), getRemotePort(), localIP(), operator=(), operator==(), pcb(), remoteIP(), send(), setKeepAlive(), setNoDelay(), space(), state(), and ~AsyncClient().
_poll_cb
AcConnectHandler AsyncClient::_poll_cb protected
Definition at line 280 of file AsyncTCP.h.
Referenced by _poll(), and onPoll().
_poll_cb_arg
void* AsyncClient::_poll_cb_arg protected
Definition at line 281 of file AsyncTCP.h.
Referenced by _poll(), and onPoll().
_recv_cb
AcDataHandler AsyncClient::_recv_cb protected
Definition at line 274 of file AsyncTCP.h.
Referenced by _recv(), AsyncClient(), and onData().
_recv_cb_arg
void* AsyncClient::_recv_cb_arg protected
Definition at line 275 of file AsyncTCP.h.
Referenced by _recv(), AsyncClient(), and onData().
_rx_ack_len
uint32_t AsyncClient::_rx_ack_len protected
Definition at line 285 of file AsyncTCP.h.
Referenced by _recv(), ack(), and close().
_rx_last_ack
uint32_t AsyncClient::_rx_last_ack protected
Definition at line 288 of file AsyncTCP.h.
Referenced by _poll(), _sent(), and AsyncClient().
_rx_last_packet
uint32_t AsyncClient::_rx_last_packet protected
Definition at line 286 of file AsyncTCP.h.
Referenced by _connected(), _poll(), _recv(), _sent(), AsyncClient(), and operator=().
_rx_timeout
uint32_t AsyncClient::_rx_timeout protected
Definition at line 287 of file AsyncTCP.h.
Referenced by _poll(), AsyncClient(), getRxTimeout(), and setRxTimeout().
_sent_cb
AcAckHandler AsyncClient::_sent_cb protected
Definition at line 270 of file AsyncTCP.h.
Referenced by _sent(), AsyncClient(), and onAck().
_sent_cb_arg
void* AsyncClient::_sent_cb_arg protected
Definition at line 271 of file AsyncTCP.h.
Referenced by _sent(), AsyncClient(), and onAck().
_timeout_cb
AcTimeoutHandler AsyncClient::_timeout_cb protected
Definition at line 278 of file AsyncTCP.h.
Referenced by _poll(), AsyncClient(), and onTimeout().
_timeout_cb_arg
void* AsyncClient::_timeout_cb_arg protected
Definition at line 279 of file AsyncTCP.h.
Referenced by _poll(), AsyncClient(), and onTimeout().
_tx_last_packet
uint32_t AsyncClient::_tx_last_packet protected
Definition at line 284 of file AsyncTCP.h.
Referenced by _poll(), _sent(), AsyncClient(), and send().
next
AsyncClient* AsyncClient::next
Definition at line 305 of file AsyncTCP.h.
Referenced by AsyncClient(), and operator+=().
prev
AsyncClient* AsyncClient::prev
Definition at line 304 of file AsyncTCP.h.
Referenced by AsyncClient(), and operator+=().
The documentation for this class was generated from the following files:
AsyncTCP.h
AsyncTCP.cpp