ESP RFID Webui: ConfigManager Class Reference
ConfigManager Class Reference
#include <ConfigManager.h>
Static Public Member Functions
static bool loadConfig (String &ssid, String &pass, String &serverBase)
static bool saveConfig (const String &ssid, const String &pass, const String &serverBase)
static String readConfigJson ()
static void listFiles ()
Static Private Attributes
static const char * CONFIG_FILE = "/config.json"
Detailed Description
Definition at line 5 of file ConfigManager.h.
Member Function Documentation
listFiles()
void ConfigManager::listFiles () static
Definition at line 93 of file ConfigManager.cpp.
{
    File root = LittleFS.open("/");
    if (!root) {
        Serial.println("LittleFS root open failed");
        return;
    }
    Serial.println("LittleFS contents:");
    File f = root.openNextFile();
    if (!f) {
        Serial.println("  (empty)");
    }
    while (f) {
        Serial.printf("  %s (%u bytes)\n", f.name(), static_cast<unsigned>(f.size()));
        f = root.openNextFile();
    }
}
loadConfig()
bool ConfigManager::loadConfig (String & ssid, String & pass, String & serverBase) static
Definition at line 18 of file ConfigManager.cpp.
{
    String json = readConfigJson();
    if (json.length() == 0) return false;
    JsonDocument doc;
    DeserializationError err = deserializeJson(doc, json);
    if (err) {
        Serial.printf("Config parse error: %s\n", err.c_str());
        return false;
    }
    ssid = String(doc["ssid"] | ssid.c_str());
    pass = String(doc["password"] | pass.c_str());
    serverBase = String(doc["server_base"] | serverBase.c_str());
    return true;
}
References readConfigJson().
Referenced by setup().
readConfigJson()
String ConfigManager::readConfigJson () static
Definition at line 69 of file ConfigManager.cpp.
{
    File f = LittleFS.open(CONFIG_FILE, "r");
    if (!f) {
        Serial.println("Config file not found");
        return {};//string
    }
    const size_t size = f.size();
    String contents;
    contents.reserve(size + 1);
    while (f.available()) {
        contents += static_cast<char>(f.read());
    }
    f.close();
    return contents;
}
References CONFIG_FILE.
Referenced by loadConfig().
saveConfig()
bool ConfigManager::saveConfig (const String & ssid, const String & pass, const String & serverBase) static
Definition at line 42 of file ConfigManager.cpp.
{
    JsonDocument doc;
    doc["ssid"] = ssid;
    doc["password"] = pass;
    doc["server_base"] = serverBase;
    File f = LittleFS.open(CONFIG_FILE, "w");
    if (!f) {
        Serial.println("Failed to open config file for writing");
        return false;
    }
    if (serializeJson(doc, f) == 0) {
        f.close();
        Serial.println("Failed to write config JSON");
        return false;
    }
    f.close();
    return true;
}
References CONFIG_FILE.
Field Documentation
CONFIG_FILE
const char * ConfigManager::CONFIG_FILE = "/config.json" static private
Definition at line 20 of file ConfigManager.h.
Referenced by readConfigJson(), and saveConfig().
The documentation for this class was generated from the following files:
ConfigManager.h
ConfigManager.cpp