ESP RFID Webui: main.cpp File Reference
main.cpp File Reference
#include <freertos/queue.h>
#include "TimerHandle.h"
#include "AuthSync.h"
#include "ConfigManager.h"
#include "HardwareSerial.h"
#include "HashUtils.h"
#include <ArduinoJson.h>
#include <HTTPClient.h>
#include <LittleFS.h>
#include <MFRC522.h>
#include <SPI.h>
#include <U8x8lib.h>
#include <WiFi.h>
#include <Wire.h>
Data Structures
struct ScanItem
Functions
MFRC522 rfid (SS_PIN, RST_PIN)
U8X8_SSD1315_128X64_NONAME_SW_I2C u8x8 (22, 21, U8X8_PIN_NONE)
String getUidString ()
void updateEnrollStatus ()
void updateDisplay ()
void drawHeader ()
void drawEnrollIndicator (bool on)
void NetworkTask (void *pv)
bool postLastScan (const String &uid, JsonDocument &out)
static void displayTimerCallback (TimerHandle_t xTimer)
void setup ()
void loop ()
void serverCheckTimerCallback (TimerHandle_t xTimer)
void authSyncTimerCallback (TimerHandle_t xTimer)
Variables
constexpr uint8_t RST_PIN = 17
constexpr uint8_t SS_PIN = 5
static constexpr unsigned long ENROLL_POLL_INTERVAL_MS = 5000
String SSID = ""
String PASS = ""
String SERVER_BASE = ""
AuthSync * authSync = nullptr
String lastUID = "NONE"
String enrollMode = "none"
bool lastAuthorized = false
uint64_t lastHash = 0
bool serverReachable = false
unsigned long lastDisplayUpdate = 0
unsigned long enrollBlinkMillis = 0
bool enrollBlinkState = false
static unsigned long lastEnrollPoll = 0
String displayedUID = ""
bool displayedAuth = false
uint64_t displayedHash = 0
String displayedEnrollMode = ""
bool displayedEnrollBlink = false
bool displayedServerReachable = false
static QueueHandle_t scanQueue = nullptr
static volatile bool authSyncRequested = false
static volatile bool displayUpdateRequested = false
Function Documentation
authSyncTimerCallback()
void authSyncTimerCallback (TimerHandle_t xTimer)
Definition at line 572 of file main.cpp.
{
  authSyncRequested = true;
}
References authSyncRequested.
Referenced by NetworkTask().
displayTimerCallback()
void displayTimerCallback (TimerHandle_t xTimer) static
Definition at line 126 of file main.cpp.
{ (void)xTimer; displayUpdateRequested = true; }
References displayUpdateRequested.
Referenced by setup().
drawEnrollIndicator()
void drawEnrollIndicator (bool on)
Definition at line 450 of file main.cpp.
{
  String currentMode = enrollMode;
  bool currentBlink = on;
  // Only redraw if mode or blink state changed - Full redraws are visible
  if (currentMode != displayedEnrollMode ||
      currentBlink != displayedEnrollBlink) {
    if (enrollMode == "none") {
      u8x8.drawString(14, 0, "  ");
    } else if (on) {
      u8x8.drawString(14, 0, enrollMode == "grant" ? "GR" : "RV");
    } else {
      u8x8.drawString(14, 0, "  ");
    }
    displayedEnrollMode = currentMode;
    displayedEnrollBlink = currentBlink;
  }
}
References displayedEnrollBlink, displayedEnrollMode, enrollMode, and u8x8().
Referenced by loop(), and updateDisplay().
drawHeader()
void drawHeader ()
Definition at line 392 of file main.cpp.
{
  static bool headerDrawn = false;
  if (!headerDrawn) {
    u8x8.clear();
    u8x8.drawString(0, 0, "RFID Access");
    headerDrawn = true;
  }
}
References u8x8().
Referenced by setup(), and updateDisplay().
getUidString()
String getUidString ()
Definition at line 380 of file main.cpp.
{
  String uid = "";
  for (byte i = 0; i < rfid.uid.size; i++) {
    if (rfid.uid.uidByte[i] < 0x10)
      uid += "0";
    uid += String(rfid.uid.uidByte[i], HEX);
  }
  uid.toUpperCase();
  return uid;
}
References rfid().
Referenced by loop().
loop()
void loop ()
Definition at line 305 of file main.cpp.
            {
  // Server reachability check now handled by FreeRTOS timer in NetworkTask
  if (rfid.PICC_IsNewCardPresent() && rfid.PICC_ReadCardSerial()) {
    String uid = getUidString();
    Serial.println("Scanned: " + uid);
    lastUID = uid;
    // Compute hash for display (same method as AuthSync) ----------- FOR
    // DEBUGGING ----
    /*String normalized = uid;
    normalized.trim();
    normalized.toUpperCase();
    uint64_t hash = 0xcbf29ce484222325ULL;
    for (size_t i = 0; i < normalized.length(); i++) {
      constexpr uint64_t prime = 0x100000001b3ULL;
      hash ^= static_cast<uint8_t>(normalized[i]);
      hash *= prime;
    }*/
    lastHash = HashUtils::hashUid(uid);
    lastAuthorized = authSync ? authSync->isAuthorized(uid) : false;
    updateEnrollStatus(); // Refresh after scan
    updateDisplay();
    rfid.PICC_HaltA();
    rfid.PCD_StopCrypto1();
    vTaskDelay(100 / portTICK_PERIOD_MS); // Debounce recommended delay
    // Defer network POST of last scan to network task via queue
    if (scanQueue) {
      ScanItem item{};
      uid.toCharArray(item.uid, sizeof(item.uid));
      if (xQueueSend(scanQueue, &item, 0) != pdPASS) {
        Serial.println("[Queue] scanQueue full; dropping UID post");
      } else {
        Serial.printf("[Queue] Enqueued UID=%s\n", item.uid);
      }
    }
  }
  // Periodic sync handled by NetworkTask
  // Display updates are requested by a timer; perform the actual update in
  // loop() context to keep display code single-threaded and safe for the
  // U8x8 library.
  if (displayUpdateRequested) {
    displayUpdateRequested = false;
    updateDisplay();
    lastDisplayUpdate = millis();
  }
  // Blink indicator when waiting for enroll
  if (enrollMode != "none" && millis() - enrollBlinkMillis > 500) {
    enrollBlinkState = !enrollBlinkState;
    enrollBlinkMillis = millis();
    drawEnrollIndicator(enrollBlinkState);
  }
  // Simple millis-based enroll-mode poll
  if (millis() - lastEnrollPoll > ENROLL_POLL_INTERVAL_MS) {
    lastEnrollPoll = millis();
    updateEnrollStatus();
  }
#ifdef AUTH_TEST_HOOK
  // Test hook: press 'm' on serial to print memory stats
  if (Serial.available()) {
    int c = Serial.read();
    if (c == 'm' || c == 'M') {
      if (authSync) authSync->TEST_dumpMemoryStats();
    }
  }
#endif
}
References authSync, displayUpdateRequested, drawEnrollIndicator(), ENROLL_POLL_INTERVAL_MS, enrollBlinkMillis, enrollBlinkState, enrollMode, getUidString(), HashUtils::hashUid(), lastAuthorized, lastDisplayUpdate, lastEnrollPoll, lastHash, lastUID, rfid(), scanQueue, ScanItem::uid, updateDisplay(), and updateEnrollStatus().
NetworkTask()
void NetworkTask (void * pv)
Definition at line 578 of file main.cpp.
{
  Serial.printf("[Tasks] NetworkTask running on core %d\n", xPortGetCoreID());
  // Create and start the timer (5000ms period, auto-reload)
  if (!createServerCheckTimer(serverCheckTimerCallback, pdMS_TO_TICKS(5000))) {
    Serial.println("[Tasks] Failed to create/start server check timer");
  } else {
    Serial.println("[Tasks] Server check timer started");
  }
  // Create and start the auth sync timer (non-blocking callback)
  if (!createAuthSyncTimer(authSyncTimerCallback, pdMS_TO_TICKS(5000))) {
    Serial.println("[Tasks] Failed to create/start auth sync timer");
  } else {
    Serial.println("[Tasks] AuthSync timer started");
  }
  for (;;) {
    // AuthSync periodic sync — triggered by timer flag (non-blocking timer
    // callback)
    if (serverReachable && authSync && authSyncRequested) {
      authSyncRequested = false; // clear flag before doing work
      authSync->update();
      Serial.println("[Tasks] Auth sync requested");
    }
    // Drain scan queue: post last_scan events (limit per cycle)
    if (serverReachable && scanQueue) {
      for (int i = 0; i < 3;
           ++i) {
        // process up to 3 per loop to avoid starving
        ScanItem item;
        if (xQueueReceive(scanQueue, &item, 0) == pdPASS) {
          // Post scan to server and handle enrollment side-effects returned by
          // the server.
          Serial.printf("[Queue] Posting UID=%s\n", item.uid);
          JsonDocument resp;
          if (postLastScan(String(item.uid), resp)) {
            Serial.printf("[Queue] postLastScan returned size=%u\n", static_cast<unsigned>(resp.size()));
            // If server acknowledged enrollment, clear enroll mode and redraw
            // indicator immediately
            if (resp.size() > 0) {
              bool enrolled = false;
              if (resp["enrolled"].is<bool>()) {
                enrolled = resp["enrolled"].as<bool>();
              }
              if (enrolled) {
                enrollMode = "none";
                // Request main loop to redraw the enroll indicator (display
                // operations must run from loop context to be thread-safe).
                displayUpdateRequested = true;
                Serial.println("[Queue] Enrollment cleared (requested display update)");
              }
            }
          } else {
            Serial.println("[Queue] postLastScan: no valid response");
          }
        } else {
          break;
        }
      }
    } else if (!serverReachable && scanQueue) {
      // When offline, keep queued scans for later (do not drop them).
      // Optionally we could limit queue size elsewhere, but avoid clearing here.
    }
    vTaskDelay(pdMS_TO_TICKS(50));
  }
}
References authSync, authSyncRequested, authSyncTimerCallback(), createAuthSyncTimer(), createServerCheckTimer(), displayUpdateRequested, enrollMode, postLastScan(), scanQueue, serverCheckTimerCallback(), serverReachable, and ScanItem::uid.
Referenced by setup().
postLastScan()
bool postLastScan (const String & uid, JsonDocument & out)
Definition at line 470 of file main.cpp.
{
  out.clear();
  // Guard: if we're offline or server not configured, return empty doc.
  // This avoids making invalid HTTP calls when no server_base is provided
  // (e.g. on first-boot before provisioning /config.json).
  if (WiFi.status() != WL_CONNECTED)
    return false;
  if (SERVER_BASE.length() == 0)
    return false;
  // Escape: if we already marked serverReachable false, skip HTTP entirely
  if (!serverReachable) {
    // Uncomment for verbose logging: Serial.println("[postLastScan] Skipped
    // (serverReachable=false)");
    return false;
  }
  HTTPClient http;
  http.setTimeout(1500); // shorter timeout to avoid long blocking
  http.begin(String(SERVER_BASE) + "/api/last_scan");
  http.addHeader("Content-Type", "application/json");
  String body = R"({"uid":")" + uid + "\"}";
  int code = http.POST(body);
  Serial.printf("[HTTP] POST /api/last_scan -> code=%d, body=%s\n", code, body.c_str());
  if (code < 200 || code >= 300) {
    Serial.printf("postLastScan failed: %d\n", code);
    http.end();
    return false;
  }
  String payload = http.getString();
  Serial.printf("[HTTP] /api/last_scan payload: %s\n", payload.c_str());
  http.end();
  // Parse into caller-provided document (prefer StaticJsonDocument in caller)
  DeserializationError err = deserializeJson(out, payload);
  if (err) {
    Serial.printf("postLastScan: JSON parse error: %s\n", err.c_str());
    out.clear();
    return false;
  }
  return true;
}
References SERVER_BASE, and serverReachable.
Referenced by NetworkTask().
rfid()
MFRC522 rfid (SS_PIN , RST_PIN)
References RST_PIN, and SS_PIN.
Referenced by getUidString(), loop(), and setup().
serverCheckTimerCallback()
void serverCheckTimerCallback (TimerHandle_t xTimer)
Definition at line 548 of file main.cpp.
{
  bool nowReachable = false;
  if (WiFiClass::status() == WL_CONNECTED && SERVER_BASE.length() > 0) {
    HTTPClient http;
    http.setTimeout(1500);
    http.begin(SERVER_BASE + "/api/status");
    int code = http.GET();
    http.end();
    nowReachable = (code == 200);
  }
  if (nowReachable != serverReachable) {
    serverReachable = nowReachable;
    Serial.printf("[DB] Reachable=%d\n", serverReachable);
    // Keep AuthSync's cached probe state in sync with the central timer so
    // both modules make decisions from the same reachability information.
    if (authSync) {
      authSync->setServerProbeResult(nowReachable, millis());
    }
  }
}
References authSync, SERVER_BASE, and serverReachable.
Referenced by NetworkTask().
setup()
void setup ()
Definition at line 129 of file main.cpp.
             {
  Serial.begin(115200);
  vTaskDelay(500 / portTICK_PERIOD_MS);
  Serial.println(" hello world!");
  // Force first auth line to render even if initial authorization is false
  // by priming displayedAuth opposite of lastAuthorized.
  displayedAuth = !lastAuthorized;
  Wire.begin(21, 22);
  u8x8.begin();
  u8x8.setFont(u8x8_font_chroma48medium8_r);
  drawHeader();
  u8x8.drawString(0, 2, "FS Init...");
  SPI.begin();
  rfid.PCD_Init();
  // Ensure FS is mounted before trying to load config
  if (LittleFS.begin()) {
    if (ConfigManager::loadConfig(SSID, PASS, SERVER_BASE)) {
      Serial.println("Config loaded from LittleFS");
      Serial.println("SSID: " + SSID);
      Serial.println("PASS: " + PASS);
      Serial.println("SERVER_BASE: " + SERVER_BASE);
      u8x8.drawString(0, 2, "FS OK   ");
      // Create AuthSync early so we can load offline caches from NVS
      if (SERVER_BASE.length() > 0) {
        authSync = new AuthSync(SERVER_BASE);
        // AuthSync constructed — delay offline preload until after WiFi
        // initialization so any network-related state is stable.
      } else {
        Serial.println("SERVER_BASE empty; offline authorization disabled "
          "until configured");
      }
    } /* -------------  If failing to flash config.json, run auto-provisioning
        ------------- Replace  this placeholder with your desired network
        details to have the device write config.json on first boot.
        ------------- ------------- ------------- ------------- -------------
        -------------*/
    /*else {
      Serial.println("config.json missing -> auto-provisioning defaults");
      // One-time provisioning: write a default config, then reload.
      if (ConfigManager::saveConfig("SSID", "PASSWORD",
  "http://SERVER_Base")) { if (ConfigManager::loadConfig(SSID, PASS,
  SERVER_BASE)) { Serial.println("Provisioned default config.json");
          Serial.println("SSID: " + SSID);
          Serial.println("PASS: " + PASS);
          Serial.println("SERVER_BASE: " + SERVER_BASE);
          u8x8.drawString(0, 2, "PROVISION");
        } else {
          Serial.println("Provision write ok but reload failed");
          u8x8.drawString(0, 2, "PROV ERR");
        }
      } else {
        Serial.println("Failed to auto-provision config.json");
        u8x8.drawString(0, 2, "PROV FAIL");
      }
    }
    ConfigManager::listFiles();
  } else {
    Serial.println("LittleFS mount failed, formatting...");
    LittleFS.format();
    if (LittleFS.begin()) {
      Serial.println("LittleFS formatted and remounted");
      if (ConfigManager::loadConfig(SSID, PASS, SERVER_BASE)) {
        Serial.println("Config loaded from LittleFS");
        ConfigManager::listFiles();
      }
    } else {
      Serial.println("LittleFS format/remount failed");
      u8x8.drawString(0, 2, "FS FAIL");
    }*/
  }
  vTaskDelay(100 /
             portTICK_PERIOD_MS); // Give some time for LittleFS to stabilize
  WiFi.begin(SSID.c_str(), PASS.c_str());
  // After Wi-Fi initialization, perform the offline preload (loads NVS + FS
  // caches) so AuthSync can have its cached data ready before any network
  // sync attempts. Doing this after WiFi.begin keeps the ordering stable.
  if (authSync) {
    authSync->preloadOffline();
    authSync->dumpMemoryStats();
    Serial.println("[AuthSync] Offline cache preloaded (after WiFi init)");
  }
  int tries = 0;
  while (WiFiClass::status() != WL_CONNECTED && tries < 80) {
    vTaskDelay(500 / portTICK_PERIOD_MS);
    Serial.print(".");
    tries++;
  }
  if (WiFiClass::status() == WL_CONNECTED) {
    Serial.println("");
    Serial.println("WiFi connected");
    Serial.print("IP address: ");
    Serial.println(WiFi.localIP());
    u8x8.drawString(0, 2, "WiFi OK     ");
    // Wifi modem sleep
    WiFi.setSleep(true);
    vTaskDelay(100 / portTICK_PERIOD_MS);
    // Attempt an online sync now that WiFi is connected (we already loaded
    // offline cache)
    bool syncOk = false;
    if (authSync) {
      // Use public begin() to perform an immediate sync (reloads NVS + attempts
      // server sync)
      syncOk = authSync->begin();
    }
    if (syncOk) {
      u8x8.drawString(0, 3, "DB OK");
      serverReachable = true;
      displayedServerReachable = true;
    } else {
      u8x8.drawString(0, 3, "DB OFFLINE  ");
      serverReachable = false;
      displayedServerReachable = false;
      Serial.println(
        "[AuthSync] Using offline cache (sync failed or server unreachable)");
    }
  } else {
    u8x8.drawString(0, 2, "WiFi FAIL");
    serverReachable = false;
    displayedServerReachable = false;
  }
  vTaskDelay(100 / portTICK_PERIOD_MS);
  // Create queue and network task (pin to core 0, lower priority than loop for
  // RFID responsiveness)
  //Note: this was implemented in a phase where there was no NetworkTask yet
  // Could probably just be lower priority
  if (!scanQueue) {
    scanQueue = xQueueCreate(10, sizeof(ScanItem));
    //Configure UNICORE flag in platformio.ini if using a single-core ESP32
#if defined(CONFIG_FREERTOS_UNICORE)
    xTaskCreate(
      NetworkTask,
      "net_task",
      4096,
      nullptr,
      tskIDLE_PRIORITY,
      nullptr);
    Serial.println("[Tasks] NetworkTask started on  IdleTask priority");
#else
    xTaskCreatePinnedToCore(
      NetworkTask,
      "net_task",
      4096,
      nullptr,
      tskIDLE_PRIORITY,
      nullptr,
      0);
    Serial.println("[Tasks] NetworkTask started on  IdleTask priority");
#endif
    // Runtime fallback: query chip info (works on Arduino and esp-idf)
    if (scanQueue) {
      Serial.println("[Tasks] scanQueue created");
    } else {
      Serial.println("[Tasks] Failed to create scanQueue");
    }
  }
  // Create timers using centralized helpers (TimerHandle.cpp)
  if (!createDisplayTimer(displayTimerCallback, pdMS_TO_TICKS(500))) {
    Serial.println("[Tasks] Failed to create/start display timer");
  } else {
    Serial.println("[Tasks] Display timer started");
  }
}
References authSync, createDisplayTimer(), displayedAuth, displayedServerReachable, displayTimerCallback(), drawHeader(), lastAuthorized, ConfigManager::loadConfig(), NetworkTask(), PASS, rfid(), scanQueue, SERVER_BASE, serverReachable, SSID, and u8x8().
u8x8()
U8X8_SSD1315_128X64_NONAME_SW_I2C u8x8 (22 , 21 , U8X8_PIN_NONE)
Referenced by drawEnrollIndicator(), drawHeader(), setup(), and updateDisplay().
updateDisplay()
void updateDisplay ()
Definition at line 402 of file main.cpp.
{
  drawHeader(); // Only draws once
  // Update DB status if changed
  if (serverReachable != displayedServerReachable) {
    if (serverReachable) {
      u8x8.drawString(0, 3, "DB OK        ");
    } else {
      u8x8.drawString(0, 3, "DB LOST      ");
    }
    displayedServerReachable = serverReachable;
  }
  // Only update UID if changed
  if (lastUID != displayedUID) {
    String line = "UID:" + lastUID;
    if (line.length() > 16)
      line = line.substring(0, 16);
    // Pad with spaces to clear old text
    while (line.length() < 16)
      line += " ";
    u8x8.drawString(0, 1, line.c_str());
    displayedUID = lastUID;
  }
  // Only update auth status if changed
  if (lastAuthorized != displayedAuth) {
    u8x8.drawString(
      0, 4, (String("Auth:") + (lastAuthorized ? "YES" : "NO ")).c_str());
    displayedAuth = lastAuthorized;
  }
  // Update hash display (last 8 hex digits on bottom row)
  if (lastHash != displayedHash) {
    char hashStr[17];
    snprintf(hashStr, sizeof(hashStr), "H:%08X",
             static_cast<uint32_t>(lastHash & 0xFFFFFFFF));
    u8x8.drawString(0, 7, hashStr);
    displayedHash = lastHash;
  }
  // Update enroll indicator if mode changed
  if (enrollMode != displayedEnrollMode) {
    drawEnrollIndicator(enrollMode != "none");
  }
}
References displayedAuth, displayedEnrollMode, displayedHash, displayedServerReachable, displayedUID, drawEnrollIndicator(), drawHeader(), enrollMode, lastAuthorized, lastHash, lastUID, serverReachable, and u8x8().
Referenced by loop().
updateEnrollStatus()
void updateEnrollStatus ()
Definition at line 512 of file main.cpp.
{
  // Skip poll if offline or no server configured. Keeps display consistent
  // and avoids pointless HTTP requests when not provisioned.
  if (WiFi.status() != WL_CONNECTED || SERVER_BASE.length() == 0) {
    enrollMode = "none";
    serverReachable = false;
    return;
  }
  // Simple synchronous status poll (called from loop() on a millis timer)
  HTTPClient http;
  http.setTimeout(1500);
  String url = SERVER_BASE + "/api/status";
  http.begin(url);
  int code = http.GET();
  if (code > 0 && code < 400)
    serverReachable = true;
  String payload = http.getString();
  JsonDocument doc;
  DeserializationError err = deserializeJson(doc, payload);
  if (!err) {
    const char *m = doc["enroll_mode"] | nullptr;
    if (m && strlen(m) > 0) {
      enrollMode = m;
    } else {
      enrollMode = "none";
    }
  } else {
    serverReachable = false;
    enrollMode = "none";
  }
  http.end();
}
References enrollMode, SERVER_BASE, and serverReachable.
Referenced by loop().
Variable Documentation
authSync
AuthSync* authSync = nullptr
Definition at line 84 of file main.cpp.
Referenced by loop(), NetworkTask(), serverCheckTimerCallback(), and setup().
authSyncRequested
volatile bool authSyncRequested = false static
Definition at line 123 of file main.cpp.
Referenced by authSyncTimerCallback(), and NetworkTask().
displayedAuth
bool displayedAuth = false
Definition at line 101 of file main.cpp.
Referenced by setup(), and updateDisplay().
displayedEnrollBlink
bool displayedEnrollBlink = false
Definition at line 104 of file main.cpp.
Referenced by drawEnrollIndicator().
displayedEnrollMode
String displayedEnrollMode = ""
Definition at line 103 of file main.cpp.
Referenced by drawEnrollIndicator(), and updateDisplay().
displayedHash
uint64_t displayedHash = 0
Definition at line 102 of file main.cpp.
Referenced by updateDisplay().
displayedServerReachable
bool displayedServerReachable = false
Definition at line 105 of file main.cpp.
Referenced by setup(), and updateDisplay().
displayedUID
String displayedUID = ""
Definition at line 100 of file main.cpp.
Referenced by updateDisplay().
displayUpdateRequested
volatile bool displayUpdateRequested = false static
Definition at line 125 of file main.cpp.
Referenced by displayTimerCallback(), loop(), and NetworkTask().
ENROLL_POLL_INTERVAL_MS
unsigned long ENROLL_POLL_INTERVAL_MS = 5000 static constexpr
Definition at line 61 of file main.cpp.
Referenced by loop().
enrollBlinkMillis
unsigned long enrollBlinkMillis = 0
Definition at line 93 of file main.cpp.
Referenced by loop().
enrollBlinkState
bool enrollBlinkState = false
Definition at line 94 of file main.cpp.
Referenced by loop().
enrollMode
String enrollMode = "none"
Definition at line 88 of file main.cpp.
Referenced by drawEnrollIndicator(), loop(), NetworkTask(), updateDisplay(), and updateEnrollStatus().
lastAuthorized
bool lastAuthorized = false
Definition at line 89 of file main.cpp.
Referenced by loop(), setup(), and updateDisplay().
lastDisplayUpdate
unsigned long lastDisplayUpdate = 0
Definition at line 92 of file main.cpp.
Referenced by loop().
lastEnrollPoll
unsigned long lastEnrollPoll = 0 static
Definition at line 97 of file main.cpp.
Referenced by loop().
lastHash
uint64_t lastHash = 0
Definition at line 90 of file main.cpp.
Referenced by loop(), and updateDisplay().
lastUID
String lastUID = "NONE"
Definition at line 87 of file main.cpp.
Referenced by loop(), and updateDisplay().
PASS
String PASS = ""
Definition at line 79 of file main.cpp.
Referenced by setup().
RST_PIN
uint8_t RST_PIN = 17 constexpr
Definition at line 59 of file main.cpp.
Referenced by rfid().
scanQueue
QueueHandle_t scanQueue = nullptr static
Definition at line 119 of file main.cpp.
Referenced by loop(), NetworkTask(), and setup().
SERVER_BASE
String SERVER_BASE = ""
Definition at line 80 of file main.cpp.
Referenced by postLastScan(), serverCheckTimerCallback(), setup(), and updateEnrollStatus().
serverReachable
bool serverReachable = false
Definition at line 91 of file main.cpp.
Referenced by NetworkTask(), postLastScan(), serverCheckTimerCallback(), setup(), updateDisplay(), and updateEnrollStatus().
SS_PIN
uint8_t SS_PIN = 5 constexpr
Definition at line 60 of file main.cpp.
Referenced by rfid().
SSID
String SSID = ""
Definition at line 78 of file main.cpp.
Referenced by setup().