ESP RFID Webui: HashUtils Namespace Reference
HashUtils Namespace Reference
Functions
uint64_t hashUid (const String &s)
Function Documentation
hashUid()
uint64_t HashUtils::hashUid (const String & s)
Definition at line 18 of file HashUtils.cpp.
{
        String t = s;
        t.trim();
        t.toUpperCase();
        return fnv1a64_bytes(reinterpret_cast<const uint8_t*>(t.c_str()), t.length());
    }
References fnv1a64_bytes().
Referenced by AuthSync::hashUid(), and loop().